<?php defined('ABSPATH') || exit; $editing=$entry instanceof \GreatMarketrealmCompanion\Modules\DungeonMaster\Models\JournalEntry; $categories=['general'=>'General Notes','npc'=>'NPC','location'=>'Location','plot-thread'=>'Plot Thread','secret'=>'Secret','lore'=>'Lore','treasure'=>'Treasure','faction'=>'Faction']; ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-journal-form__body">
<input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($route); ?>"><input type="hidden" name="_method" value="<?php echo $editing?'PUT':'POST'; ?>"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_journal_'.$campaign->id())); ?>">
<div class="gmrc-journal-form__row"><label>Category<select name="category"><?php foreach($categories as $key=>$label): ?><option value="<?php echo esc_attr($key); ?>" <?php selected($editing?$entry->category():'general',$key); ?>><?php echo esc_html($label); ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="active" <?php selected($editing?$entry->status():'active','active'); ?>>Active</option><option value="resolved" <?php selected($editing?$entry->status():'active','resolved'); ?>>Resolved</option><option value="archived" <?php selected($editing?$entry->status():'active','archived'); ?>>Archived</option></select></label><label>Related Session<select name="session_id"><option value="">Campaign-wide</option><?php foreach(($sessions??[]) as $session): ?><option value="<?php echo esc_attr($session->id()); ?>" <?php selected($editing?$entry->sessionId():'',$session->id()); ?>>Session <?php echo esc_html((string)$session->number()); ?> · <?php echo esc_html($session->title()); ?></option><?php endforeach; ?></select></label></div>
<label>Journal heading<input type="text" name="title" maxlength="140" required value="<?php echo esc_attr($editing?$entry->title():''); ?>"></label>
<label>Private Dungeon Master notes<textarea name="journal_content" rows="14" maxlength="20000" required><?php echo esc_textarea($editing?$entry->content():''); ?></textarea></label>
<label class="gmrc-journal-pin"><input type="checkbox" name="pinned" value="1" <?php checked($editing&&$entry->pinned()); ?>> Pin this note to the top of the Journal</label>
<button class="gmrc-journal-button" type="submit"><?php echo $editing?'Update Journal Entry':'Write in Campaign Journal'; ?></button>
</form>
