<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers;
use GreatMarketrealmCompanion\Core\Http\RedirectResponse;use GreatMarketrealmCompanion\Core\Http\ResponseFactory;use GreatMarketrealmCompanion\Core\Session\FlashStore;use GreatMarketrealmCompanion\Core\View\View;use GreatMarketrealmCompanion\Core\View\ViewFactory;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\EvidenceRecord;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Location;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Persona;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\CampaignRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\EvidenceRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\LocationRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\PersonaRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Requests\SaveEvidenceRequest;use GreatMarketrealmCompanion\Modules\DungeonMaster\Services\DungeonMasterAccess;use RuntimeException;
defined('ABSPATH') || exit;
final class EvidenceController
{
 public function __construct(private CampaignRepository $campaigns,private EvidenceRepository $evidence,private LocationRepository $locations,private PersonaRepository $personae,private DungeonMasterAccess $access,private ViewFactory $views,private ResponseFactory $responses,private FlashStore $flash){}
 public function index(string $id):string{$campaign=$this->campaign($id);return $this->render('dungeonmaster.evidence.index',$campaign,['records'=>$this->evidence->allForCampaign($campaign)]);}
 public function create(string $id):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.evidence.create',$campaign,$this->choices($campaign)+['record'=>null]);}
 public function store(string $id,SaveEvidenceRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);[$threads,$locations,$personae]=$this->validLinks($request,$campaign);$record=EvidenceRecord::create($campaign->id(),$campaign->ownerId(),$request->name(),$request->recordType(),$request->evidenceKind(),$request->summary(),$request->notes(),$request->visibility(),$request->recordType()==='thread'?[]:$threads,$locations,$personae);$this->evidence->save($record,$campaign);$this->flash->success($record->isThread()?'The thread has been opened in the Evidence Register.':'The evidence has been entered into the Register.');return $this->responses->redirect($this->showUrl($campaign->id(),$record->id()));}
 public function show(string $id,string $evidenceId):string{$campaign=$this->campaign($id);$record=$this->record($evidenceId,$campaign);$all=$this->evidence->allForCampaign($campaign);$linkedEvidence=$record->isThread()?array_values(array_filter($all,static fn(EvidenceRecord $r):bool=>!$r->isArchived()&&in_array($record->id(),$r->threadIds(),true))):[];return $this->render('dungeonmaster.evidence.show',$campaign,$this->choices($campaign)+['record'=>$record,'linkedEvidence'=>$linkedEvidence]);}
 public function edit(string $id,string $evidenceId):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.evidence.edit',$campaign,$this->choices($campaign)+['record'=>$this->record($evidenceId,$campaign)]);}
 public function update(string $id,string $evidenceId,SaveEvidenceRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$record=$this->record($evidenceId,$campaign);if($record->isThread()&&$request->recordType()==='evidence'&&$this->linkedEvidence($record->id(),$campaign)!==[]){throw new RuntimeException('Move the active evidence off this thread before changing it into evidence.');}[$threads,$locations,$personae]=$this->validLinks($request,$campaign,$record->id());$record->update($request->name(),$request->recordType(),$request->evidenceKind(),$request->summary(),$request->notes(),$request->visibility(),$request->recordType()==='thread'?[]:$threads,$locations,$personae);$this->evidence->save($record,$campaign);$this->flash->success('The Evidence Register record has been updated.');return $this->responses->redirect($this->showUrl($campaign->id(),$record->id()));}
 public function archive(string $id,string $evidenceId):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$record=$this->record($evidenceId,$campaign);if($record->isThread()&&$this->linkedEvidence($record->id(),$campaign)!==[]){throw new RuntimeException('Move or archive the evidence attached to this thread before archiving it.');}$record->archive();$this->evidence->save($record,$campaign);$this->flash->success('The Evidence Register record has been archived.');return $this->responses->redirect($this->indexUrl($campaign->id()));}
 private function campaign(string $id):Campaign{if(!$this->access->allows()){status_header(403);throw new RuntimeException('The Evidence Register is sealed to Dungeon Masters.');}$campaign=$this->campaigns->findForOwner($id,get_current_user_id());if(!$campaign instanceof Campaign){throw new RuntimeException('Campaign not found in this Dungeon Master’s Register.');}return $campaign;}
 private function record(string $id,Campaign $campaign):EvidenceRecord{$record=$this->evidence->findForCampaign($id,$campaign);if(!$record instanceof EvidenceRecord){throw new RuntimeException('Evidence Register record not found in this Campaign.');}return $record;}
 private function assertActive(Campaign $campaign):void{if($campaign->isArchived()){throw new RuntimeException('Archived campaigns have a read-only Evidence Register.');}}
 /** @return array{0:list<string>,1:list<string>,2:list<string>} */private function validLinks(SaveEvidenceRequest $request,Campaign $campaign,string $recordId=''):array{$threads=$this->validateIds($request->threadIds(),$this->activeThreads($campaign),$recordId,'thread');$locations=$this->validateIds($request->locationIds(),$this->activeLocations($campaign),'','location');$personae=$this->validateIds($request->personaIds(),$this->activePersonae($campaign),'','person or faction');return [$threads,$locations,$personae];}
 /** @param list<string> $ids @param array<int,object> $available @return list<string> */private function validateIds(array $ids,array $available,string $forbidden,string $label):array{$allowed=[];foreach($available as $item){if(method_exists($item,'id')){$allowed[$item->id()]=true;}}foreach($ids as $id){if($id===$forbidden||!isset($allowed[$id])){throw new RuntimeException('Every selected '.$label.' must be an active record in this Campaign.');}}return array_values(array_unique($ids));}
 /** @return EvidenceRecord[] */private function activeThreads(Campaign $campaign):array{return array_values(array_filter($this->evidence->allForCampaign($campaign),static fn(EvidenceRecord $r):bool=>$r->isThread()&&!$r->isArchived()));}/** @return Location[] */private function activeLocations(Campaign $campaign):array{return array_values(array_filter($this->locations->allForCampaign($campaign),static fn(Location $l):bool=>!$l->isArchived()));}/** @return Persona[] */private function activePersonae(Campaign $campaign):array{return array_values(array_filter($this->personae->allForCampaign($campaign),static fn(Persona $p):bool=>!$p->isArchived()));}/** @return EvidenceRecord[] */private function linkedEvidence(string $threadId,Campaign $campaign):array{return array_values(array_filter($this->evidence->allForCampaign($campaign),static fn(EvidenceRecord $r):bool=>!$r->isArchived()&&in_array($threadId,$r->threadIds(),true)));}
 /** @return array{threads:array,locations:array,personae:array} */private function choices(Campaign $campaign):array{return ['threads'=>$this->activeThreads($campaign),'locations'=>$this->activeLocations($campaign),'personae'=>$this->activePersonae($campaign)];}
 private function render(string $view,Campaign $campaign,array $extra):string{return $this->views->render(View::make($view,array_merge(['campaign'=>$campaign,'flash'=>['success'=>$this->flash->get('success'),'error'=>$this->flash->get('error')]],$extra)));}private function indexUrl(string $campaignId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/evidence',home_url('/companion/'));}private function showUrl(string $campaignId,string $evidenceId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/evidence/'.$evidenceId,home_url('/companion/'));}
}
