<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers;
use GreatMarketrealmCompanion\Core\Http\RedirectResponse;use GreatMarketrealmCompanion\Core\Http\ResponseFactory;use GreatMarketrealmCompanion\Core\Session\FlashStore;use GreatMarketrealmCompanion\Core\View\View;use GreatMarketrealmCompanion\Core\View\ViewFactory;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\JournalEntry;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\CampaignRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\JournalRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\SessionRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Requests\SaveJournalEntryRequest;use GreatMarketrealmCompanion\Modules\DungeonMaster\Services\DungeonMasterAccess;use RuntimeException;
defined('ABSPATH') || exit;
final class JournalController
{
 public function __construct(private CampaignRepository $campaigns,private JournalRepository $journal,private SessionRepository $sessions,private DungeonMasterAccess $access,private ViewFactory $views,private ResponseFactory $responses,private FlashStore $flash){}
 public function index(string $id): string{$campaign=$this->campaign($id);return $this->render('dungeonmaster.journal.index',$campaign,['entries'=>$this->journal->allForCampaign($campaign),'sessions'=>$this->sessions->allForCampaign($campaign)]);}
 public function create(string $id): string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.journal.create',$campaign,['entry'=>null,'sessions'=>$this->sessions->allForCampaign($campaign)]);}
 public function store(string $id,SaveJournalEntryRequest $request): RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$sessionId=$this->validSessionId($request->sessionId(),$campaign);$entry=JournalEntry::create($campaign->id(),$campaign->ownerId(),$request->title(),$request->category(),$request->content(),$request->status(),$sessionId,$request->pinned());$this->journal->save($entry,$campaign);$this->flash->success('The note has been entered into the Campaign Journal.');return $this->responses->redirect($this->showUrl($campaign->id(),$entry->id()));}
 public function show(string $id,string $journalId): string{$campaign=$this->campaign($id);$entry=$this->entry($journalId,$campaign);return $this->render('dungeonmaster.journal.show',$campaign,['entry'=>$entry,'linkedSession'=>$entry->sessionId()!==''?$this->sessions->findForCampaign($entry->sessionId(),$campaign):null]);}
 public function edit(string $id,string $journalId): string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.journal.edit',$campaign,['entry'=>$this->entry($journalId,$campaign),'sessions'=>$this->sessions->allForCampaign($campaign)]);}
 public function update(string $id,string $journalId,SaveJournalEntryRequest $request): RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$entry=$this->entry($journalId,$campaign);$entry->update($request->title(),$request->category(),$request->content(),$request->status(),$this->validSessionId($request->sessionId(),$campaign),$request->pinned());$this->journal->save($entry,$campaign);$this->flash->success('The Campaign Journal entry has been updated.');return $this->responses->redirect($this->showUrl($campaign->id(),$entry->id()));}
 public function archive(string $id,string $journalId): RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$entry=$this->entry($journalId,$campaign);$entry->archive();$this->journal->save($entry,$campaign);$this->flash->success('The Journal entry has been archived.');return $this->responses->redirect($this->indexUrl($campaign->id()));}
 private function campaign(string $id): Campaign{if(!$this->access->allows()){status_header(403);throw new RuntimeException('The Campaign Journal is sealed to Dungeon Masters.');}$campaign=$this->campaigns->findForOwner($id,get_current_user_id());if(!$campaign instanceof Campaign){throw new RuntimeException('Campaign not found in this Dungeon Master’s Register.');}return $campaign;}
 private function entry(string $id,Campaign $campaign): JournalEntry{$entry=$this->journal->findForCampaign($id,$campaign);if(!$entry instanceof JournalEntry){throw new RuntimeException('Journal entry not found in this Campaign.');}return $entry;}
 private function assertActive(Campaign $campaign): void{if($campaign->isArchived()){throw new RuntimeException('Archived campaigns have a read-only Campaign Journal.');}}
 private function validSessionId(string $sessionId,Campaign $campaign): string{if($sessionId===''){return '';}$session=$this->sessions->findForCampaign($sessionId,$campaign);if($session===null){throw new RuntimeException('The linked Session does not belong to this Campaign.');}return $sessionId;}
 private function render(string $view,Campaign $campaign,array $extra): string{return $this->views->render(View::make($view,array_merge(['campaign'=>$campaign,'flash'=>['success'=>$this->flash->get('success'),'error'=>$this->flash->get('error')]],$extra)));}
 private function indexUrl(string $campaignId): string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/journal',home_url('/companion/'));}
 private function showUrl(string $campaignId,string $journalId): string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/journal/'.$journalId,home_url('/companion/'));}
}