<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers;
use GreatMarketrealmCompanion\Core\Http\RedirectResponse;use GreatMarketrealmCompanion\Core\Http\ResponseFactory;use GreatMarketrealmCompanion\Core\Session\FlashStore;use GreatMarketrealmCompanion\Core\View\View;use GreatMarketrealmCompanion\Core\View\ViewFactory;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Location;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\CampaignRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\LocationRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Requests\SaveLocationRequest;use GreatMarketrealmCompanion\Modules\DungeonMaster\Services\DungeonMasterAccess;use RuntimeException;
defined('ABSPATH') || exit;
final class LocationController
{
 public function __construct(private CampaignRepository $campaigns,private LocationRepository $locations,private DungeonMasterAccess $access,private ViewFactory $views,private ResponseFactory $responses,private FlashStore $flash){}
 public function index(string $id):string{$campaign=$this->campaign($id);return $this->render('dungeonmaster.locations.index',$campaign,['locations'=>$this->locations->allForCampaign($campaign)]);}
 public function create(string $id):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.locations.create',$campaign,['location'=>null,'locations'=>$this->locations->allForCampaign($campaign)]);}
 public function store(string $id,SaveLocationRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$parentId=$this->validParentId($request->parentId(),$campaign,'');$location=Location::create($campaign->id(),$campaign->ownerId(),$request->name(),$request->type(),$request->summary(),$request->notes(),$parentId,$request->visibility());$this->locations->save($location,$campaign);$this->flash->success('The location has been entered into the Keeper’s Gazetteer.');return $this->responses->redirect($this->showUrl($campaign->id(),$location->id()));}
 public function show(string $id,string $locationId):string{$campaign=$this->campaign($id);$location=$this->location($locationId,$campaign);return $this->render('dungeonmaster.locations.show',$campaign,['location'=>$location,'parent'=>$location->parentId()!==''?$this->locations->findForCampaign($location->parentId(),$campaign):null,'children'=>$this->childrenOf($location->id(),$campaign)]);}
 public function edit(string $id,string $locationId):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.locations.edit',$campaign,['location'=>$this->location($locationId,$campaign),'locations'=>$this->locations->allForCampaign($campaign)]);}
 public function update(string $id,string $locationId,SaveLocationRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$location=$this->location($locationId,$campaign);$parentId=$this->validParentId($request->parentId(),$campaign,$location->id());$location->update($request->name(),$request->type(),$request->summary(),$request->notes(),$parentId,$request->visibility());$this->locations->save($location,$campaign);$this->flash->success('The Gazetteer location has been updated.');return $this->responses->redirect($this->showUrl($campaign->id(),$location->id()));}
 public function archive(string $id,string $locationId):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$location=$this->location($locationId,$campaign);if($this->childrenOf($location->id(),$campaign)!==[]){throw new RuntimeException('Move or archive this location’s child places before archiving it.');}$location->archive();$this->locations->save($location,$campaign);$this->flash->success('The location has been archived in the Keeper’s Gazetteer.');return $this->responses->redirect($this->indexUrl($campaign->id()));}
 private function campaign(string $id):Campaign{if(!$this->access->allows()){status_header(403);throw new RuntimeException('The Keeper’s Gazetteer is sealed to Dungeon Masters.');}$campaign=$this->campaigns->findForOwner($id,get_current_user_id());if(!$campaign instanceof Campaign){throw new RuntimeException('Campaign not found in this Dungeon Master’s Register.');}return $campaign;}
 private function location(string $id,Campaign $campaign):Location{$location=$this->locations->findForCampaign($id,$campaign);if(!$location instanceof Location){throw new RuntimeException('Location not found in this Campaign Gazetteer.');}return $location;}
 private function assertActive(Campaign $campaign):void{if($campaign->isArchived()){throw new RuntimeException('Archived campaigns have a read-only Keeper’s Gazetteer.');}}
 private function validParentId(string $parentId,Campaign $campaign,string $locationId):string{if($parentId===''){return '';}if($parentId===$locationId){throw new RuntimeException('A Gazetteer location cannot contain itself.');}$parent=$this->locations->findForCampaign($parentId,$campaign);if(!$parent instanceof Location||$parent->isArchived()){throw new RuntimeException('The parent location must be an active place in this Campaign.');}$seen=[];$cursor=$parent;while($cursor instanceof Location&&$cursor->parentId()!==''){if(isset($seen[$cursor->id()])||$cursor->parentId()===$locationId){throw new RuntimeException('That parent would create a circular Gazetteer location tree.');}$seen[$cursor->id()]=true;$cursor=$this->locations->findForCampaign($cursor->parentId(),$campaign);}return $parentId;}
 /** @return Location[] */private function childrenOf(string $parentId,Campaign $campaign):array{return array_values(array_filter($this->locations->allForCampaign($campaign),static fn(Location $candidate):bool=>$candidate->parentId()===$parentId&& !$candidate->isArchived()));}
 private function render(string $view,Campaign $campaign,array $extra):string{return $this->views->render(View::make($view,array_merge(['campaign'=>$campaign,'flash'=>['success'=>$this->flash->get('success'),'error'=>$this->flash->get('error')]],$extra)));}private function indexUrl(string $campaignId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/locations',home_url('/companion/'));}private function showUrl(string $campaignId,string $locationId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/locations/'.$locationId,home_url('/companion/'));}
}
