<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers;
use GreatMarketrealmCompanion\Core\Http\RedirectResponse;use GreatMarketrealmCompanion\Core\Http\ResponseFactory;use GreatMarketrealmCompanion\Core\Session\FlashStore;use GreatMarketrealmCompanion\Core\View\View;use GreatMarketrealmCompanion\Core\View\ViewFactory;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Persona;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\CampaignRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\PersonaRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Requests\SavePersonaRequest;use GreatMarketrealmCompanion\Modules\DungeonMaster\Services\DungeonMasterAccess;use RuntimeException;
defined('ABSPATH') || exit;
final class PersonaController
{
 public function __construct(private CampaignRepository $campaigns,private PersonaRepository $personae,private DungeonMasterAccess $access,private ViewFactory $views,private ResponseFactory $responses,private FlashStore $flash){}
 public function index(string $id):string{$campaign=$this->campaign($id);return $this->render('dungeonmaster.personae.index',$campaign,['personae'=>$this->personae->allForCampaign($campaign)]);}
 public function create(string $id):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.personae.create',$campaign,['persona'=>null,'factions'=>$this->activeFactions($campaign)]);}
 public function store(string $id,SavePersonaRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$factionId=$this->validFactionId($request->kind(),$request->factionId(),$campaign);$persona=Persona::create($campaign->id(),$campaign->ownerId(),$request->name(),$request->kind(),$request->role(),$request->summary(),$request->notes(),$request->visibility(),$factionId);$this->personae->save($persona,$campaign);$this->flash->success($persona->isFaction()?'The faction has been entered into Dramatis Personae.':'The person has been entered into Dramatis Personae.');return $this->responses->redirect($this->showUrl($campaign->id(),$persona->id()));}
 public function show(string $id,string $personaId):string{$campaign=$this->campaign($id);$persona=$this->persona($personaId,$campaign);$faction=$persona->factionId()!==''?$this->personae->findForCampaign($persona->factionId(),$campaign):null;$members=$persona->isFaction()?array_values(array_filter($this->personae->allForCampaign($campaign),static fn(Persona $p):bool=>$p->factionId()===$persona->id()&&!$p->isArchived())):[];return $this->render('dungeonmaster.personae.show',$campaign,['persona'=>$persona,'faction'=>$faction,'members'=>$members]);}
 public function edit(string $id,string $personaId):string{$campaign=$this->campaign($id);$this->assertActive($campaign);return $this->render('dungeonmaster.personae.edit',$campaign,['persona'=>$this->persona($personaId,$campaign),'factions'=>$this->activeFactions($campaign)]);}
 public function update(string $id,string $personaId,SavePersonaRequest $request):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$persona=$this->persona($personaId,$campaign);if($persona->isFaction()&&$request->kind()==='person'&&$this->activeMembers($persona->id(),$campaign)!==[]){throw new RuntimeException('Move this faction’s active members before changing it into a person.');}$factionId=$this->validFactionId($request->kind(),$request->factionId(),$campaign,$persona->id());$persona->update($request->name(),$request->kind(),$request->role(),$request->summary(),$request->notes(),$request->visibility(),$factionId);$this->personae->save($persona,$campaign);$this->flash->success('The Dramatis Personae record has been updated.');return $this->responses->redirect($this->showUrl($campaign->id(),$persona->id()));}
 public function archive(string $id,string $personaId):RedirectResponse{$campaign=$this->campaign($id);$this->assertActive($campaign);$persona=$this->persona($personaId,$campaign);if($persona->isFaction()&&$this->activeMembers($persona->id(),$campaign)!==[]){throw new RuntimeException('Move or archive this faction’s active members before archiving it.');}$persona->archive();$this->personae->save($persona,$campaign);$this->flash->success('The Dramatis Personae record has been archived.');return $this->responses->redirect($this->indexUrl($campaign->id()));}
 private function campaign(string $id):Campaign{if(!$this->access->allows()){status_header(403);throw new RuntimeException('Dramatis Personae is sealed to Dungeon Masters.');}$campaign=$this->campaigns->findForOwner($id,get_current_user_id());if(!$campaign instanceof Campaign){throw new RuntimeException('Campaign not found in this Dungeon Master’s Register.');}return $campaign;}
 private function persona(string $id,Campaign $campaign):Persona{$persona=$this->personae->findForCampaign($id,$campaign);if(!$persona instanceof Persona){throw new RuntimeException('Person or faction not found in this Campaign.');}return $persona;}
 private function assertActive(Campaign $campaign):void{if($campaign->isArchived()){throw new RuntimeException('Archived campaigns have a read-only Dramatis Personae.');}}
 private function validFactionId(string $kind,string $factionId,Campaign $campaign,string $personaId=''):string{if($kind==='faction'||$factionId===''){return '';}if($factionId===$personaId){throw new RuntimeException('A person cannot name themselves as a faction.');}$faction=$this->personae->findForCampaign($factionId,$campaign);if(!$faction instanceof Persona||!$faction->isFaction()||$faction->isArchived()){throw new RuntimeException('The selected faction must be an active faction in this Campaign.');}return $factionId;}
 /** @return Persona[] */private function activeFactions(Campaign $campaign):array{return array_values(array_filter($this->personae->allForCampaign($campaign),static fn(Persona $p):bool=>$p->isFaction()&&!$p->isArchived()));}
 /** @return Persona[] */private function activeMembers(string $factionId,Campaign $campaign):array{return array_values(array_filter($this->personae->allForCampaign($campaign),static fn(Persona $p):bool=>$p->factionId()===$factionId&&!$p->isArchived()));}
 private function render(string $view,Campaign $campaign,array $extra):string{return $this->views->render(View::make($view,array_merge(['campaign'=>$campaign,'flash'=>['success'=>$this->flash->get('success'),'error'=>$this->flash->get('error')]],$extra)));}private function indexUrl(string $campaignId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/personae',home_url('/companion/'));}private function showUrl(string $campaignId,string $personaId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/personae/'.$personaId,home_url('/companion/'));}
}
