<?php defined('ABSPATH') || exit; $editing=$encounter instanceof \GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Encounter; $selected=$editing?$encounter->characterIds():[]; ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-encounter-form__body">
<input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($route); ?>"><input type="hidden" name="_method" value="<?php echo $editing?'PUT':'POST'; ?>"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_encounter_'.$campaign->id())); ?>">
<label>Encounter title<input type="text" name="title" maxlength="120" required value="<?php echo esc_attr($editing?$encounter->title():''); ?>"></label>
<div class="gmrc-encounter-form__row"><label>Status<select name="status"><option value="prepared" <?php selected($editing?$encounter->status():'prepared','prepared'); ?>>Prepared</option><option value="running" <?php selected($editing?$encounter->status():'prepared','running'); ?>>Running</option><option value="completed" <?php selected($editing?$encounter->status():'prepared','completed'); ?>>Completed</option></select></label><label>Threat<select name="threat"><option value="low" <?php selected($editing?$encounter->threat():'moderate','low'); ?>>Low</option><option value="moderate" <?php selected($editing?$encounter->threat():'moderate','moderate'); ?>>Moderate</option><option value="high" <?php selected($editing?$encounter->threat():'moderate','high'); ?>>High</option><option value="deadly" <?php selected($editing?$encounter->threat():'moderate','deadly'); ?>>Deadly</option></select></label><label>Session<select name="session_id"><option value="">Unassigned / future encounter</option><?php foreach(($sessions??[]) as $entry): ?><option value="<?php echo esc_attr($entry->id()); ?>" <?php selected($editing?$encounter->sessionId():'',$entry->id()); ?>>Session <?php echo esc_html((string)$entry->number().' — '.$entry->title()); ?></option><?php endforeach; ?></select></label></div>
<label>Location / environment<input type="text" name="location" maxlength="160" value="<?php echo esc_attr($editing?$encounter->location():''); ?>"></label>
<label>Adversary roster<textarea name="adversaries" rows="7" maxlength="5000" placeholder="List creatures, groups, hazards or other opposition. One per line works beautifully."><?php echo esc_textarea($editing?$encounter->adversaries():''); ?></textarea></label>
<label>Dungeon Master notes<textarea name="notes" rows="8" maxlength="10000"><?php echo esc_textarea($editing?$encounter->notes():''); ?></textarea></label>
<fieldset class="gmrc-encounter-party"><legend>Participating adventurers</legend><p>Only Characters already attached to this Campaign through the Player Roster can be selected.</p><?php if(($characters??[])===[]): ?><p>No campaign Characters are attached yet. The Encounter can still be prepared now.</p><?php endif; ?><div class="gmrc-encounter-party__grid"><?php foreach(($characters??[]) as $character): $cid=$character->id()->value(); ?><label><input type="checkbox" name="character_ids[]" value="<?php echo esc_attr($cid); ?>" <?php checked(in_array($cid,$selected,true)); ?>><?php echo esc_html($character->name()->value()); ?></label><?php endforeach; ?></div></fieldset>
<button class="gmrc-encounter-button" type="submit"><?php echo $editing?'Update Encounter':'Pin Encounter to Board'; ?></button>
</form>
