<?php defined('ABSPATH') || exit;$base=home_url('/companion/');$root='dungeon-master/campaigns/'.$campaign->id().'/conspiracy-board';$defaults=['location'=>[10,12],'person'=>[38,10],'faction'=>[68,12],'evidence'=>[18,55],'thread'=>[62,55]];$counts=[];foreach($pins as $pin){$counts[$pin['type']]=($counts[$pin['type']]??0)+1;} ?>
<section class="gmrc-conspiracy" data-gmrc-conspiracy-board>
 <header class="gmrc-conspiracy__hero"><div><p class="gmrc-dm-desk__eyebrow">Keeper’s Workshop · <?php echo esc_html($campaign->name()); ?></p><h1>The Conspiracy Board</h1><p>Every card is a window into a canonical campaign record. Move the pins; follow the strings; do not trust the cheese.</p></div><a class="gmrc-conspiracy__return" href="<?php echo esc_url(add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaign->id(),$base)); ?>">Campaign Command Centre</a></header>
 <?php if(!empty($flash['success'])):?><p class="gmrc-conspiracy__notice" role="status"><?php echo esc_html($flash['success']); ?></p><?php endif; ?>
 <nav class="gmrc-conspiracy__legend" aria-label="Board legend"><span>🗺️ Locations</span><span>👤 People</span><span>🎭 Factions</span><span>🔎 Evidence</span><span>🧵 Threads</span><strong><?php echo count($pins); ?> pins · <?php echo count($connections); ?> strings</strong></nav>
 <?php if($pins===[]): ?><article class="gmrc-conspiracy__empty"><div>🧀</div><h2>Nothing suspicious. Yet.</h2><p>Add locations, people, factions, evidence or threads to this campaign and their canonical records will appear here automatically.</p></article><?php else: ?>
 <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-conspiracy__form"><input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($root); ?>"><input type="hidden" name="_method" value="POST"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_conspiracy_board_'.$campaign->id())); ?>"><input type="hidden" name="positions" value="{}" data-gmrc-board-positions>
 <div class="gmrc-conspiracy__board" data-gmrc-board-canvas data-connections="<?php echo esc_attr(wp_json_encode($connections)); ?>"><svg class="gmrc-conspiracy__strings" aria-hidden="true" data-gmrc-board-strings></svg>
 <?php $typeIndex=[];foreach($pins as $pin):$i=$typeIndex[$pin['type']]??0;$typeIndex[$pin['type']]=$i+1;$fallback=$defaults[$pin['type']]??[10,10];$pos=$positions[$pin['key']]??['x'=>min(84,$fallback[0]+(($i%3)*8)),'y'=>min(82,$fallback[1]+(intdiv($i,3)*15))]; ?>
  <article class="gmrc-conspiracy-pin gmrc-conspiracy-pin--<?php echo esc_attr($pin['type']); ?>" data-pin-key="<?php echo esc_attr($pin['key']); ?>" style="left:<?php echo esc_attr((string)$pos['x']); ?>%;top:<?php echo esc_attr((string)$pos['y']); ?>%;"><button type="button" class="gmrc-conspiracy-pin__tack" aria-label="Move <?php echo esc_attr($pin['name']); ?>">●</button><p><?php echo esc_html($pin['label']); ?></p><h2><?php echo esc_html($pin['name']); ?></h2><?php if($pin['summary']!==''):?><small><?php echo esc_html($pin['summary']); ?></small><?php endif;?><a href="<?php echo esc_url($pin['route']); ?>">Open record →</a></article>
 <?php endforeach; ?></div>
 <?php if(!$campaign->isArchived()):?><div class="gmrc-conspiracy__actions"><p>Drag a pin by its tack. The red strings are drawn from relationships already recorded in the Gazetteer, Dramatis Personae and Evidence Register.</p><button type="submit">Save Board Layout</button></div><?php endif;?></form><?php endif;?>
</section>
