<?php defined('ABSPATH') || exit;$base=home_url('/companion/');$root='dungeon-master/campaigns/'.$campaign->id().'/conspiracy-board';$defaults=['location'=>[10,12],'person'=>[38,10],'faction'=>[68,12],'evidence'=>[18,55],'thread'=>[62,55]]; ?>
<section class="gmrc-conspiracy" data-gmrc-conspiracy-board data-board-readonly="<?php echo $campaign->isArchived()?'1':'0'; ?>">
 <header class="gmrc-conspiracy__hero"><div><p class="gmrc-dm-desk__eyebrow">Keeper’s Workshop · <?php echo esc_html($campaign->name()); ?></p><h1>The Conspiracy Board</h1><p>Every record card stays canonical. Board notes, labels and loose pins belong only to this investigation.</p></div><a class="gmrc-conspiracy__return" href="<?php echo esc_url(add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaign->id(),$base)); ?>">Campaign Command Centre</a></header>
 <?php if(!empty($flash['success'])):?><p class="gmrc-conspiracy__notice" role="status"><?php echo esc_html($flash['success']); ?></p><?php endif; ?>
 <nav class="gmrc-conspiracy__legend" aria-label="Board filters"><button type="button" data-board-filter="location" aria-pressed="false">🗺️ Locations</button><button type="button" data-board-filter="person" aria-pressed="false">👤 People</button><button type="button" data-board-filter="faction" aria-pressed="false">🎭 Factions</button><button type="button" data-board-filter="evidence" aria-pressed="false">🔎 Evidence</button><button type="button" data-board-filter="thread" aria-pressed="false">🧵 Threads</button><strong><?php echo count($pins); ?> records · <?php echo count($annotations); ?> board items · <?php echo count($connections)+count($manualConnections); ?> strings</strong></nav>
 <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-conspiracy__form"><input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($root); ?>"><input type="hidden" name="_method" value="POST"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_conspiracy_board_'.$campaign->id())); ?>"><input type="hidden" name="positions" value="{}" data-gmrc-board-positions><input type="hidden" name="annotations" value="<?php echo esc_attr(wp_json_encode($annotations)); ?>" data-gmrc-board-annotations><input type="hidden" name="manual_connections" value="<?php echo esc_attr(wp_json_encode($manualConnections)); ?>" data-gmrc-board-manual-connections>
 <div class="gmrc-conspiracy__board" data-gmrc-board-canvas data-connections="<?php echo esc_attr(wp_json_encode($connections)); ?>"><svg class="gmrc-conspiracy__strings" aria-hidden="true" data-gmrc-board-strings></svg>
 <?php $typeIndex=[];foreach($pins as $pin):$i=$typeIndex[$pin['type']]??0;$typeIndex[$pin['type']]=$i+1;$fallback=$defaults[$pin['type']]??[10,10];$pos=$positions[$pin['key']]??['x'=>min(84,$fallback[0]+(($i%3)*8)),'y'=>min(82,$fallback[1]+(intdiv($i,3)*15))]; ?>
  <article class="gmrc-conspiracy-pin gmrc-conspiracy-pin--<?php echo esc_attr($pin['type']); ?>" data-pin-key="<?php echo esc_attr($pin['key']); ?>" data-board-key="<?php echo esc_attr($pin['key']); ?>" data-board-type="<?php echo esc_attr($pin['type']); ?>" style="left:<?php echo esc_attr((string)$pos['x']); ?>%;top:<?php echo esc_attr((string)$pos['y']); ?>%;"><button type="button" class="gmrc-conspiracy-pin__tack" aria-label="Move <?php echo esc_attr($pin['name']); ?>">●</button><p><?php echo esc_html($pin['label']); ?></p><h2><?php echo esc_html($pin['name']); ?></h2><?php if($pin['summary']!==''):?><small><?php echo esc_html($pin['summary']); ?></small><?php endif;?><a href="<?php echo esc_url($pin['route']); ?>">Open record →</a></article>
 <?php endforeach; ?>
 <?php foreach($annotations as $annotation): ?><article class="gmrc-board-annotation gmrc-board-annotation--<?php echo esc_attr($annotation['type']); ?>" data-board-annotation data-board-key="board-<?php echo esc_attr($annotation['id']); ?>" data-annotation-id="<?php echo esc_attr($annotation['id']); ?>" data-annotation-type="<?php echo esc_attr($annotation['type']); ?>" style="left:<?php echo esc_attr((string)$annotation['x']); ?>%;top:<?php echo esc_attr((string)$annotation['y']); ?>%;"><button type="button" class="gmrc-board-annotation__tack" aria-label="Move board item">●</button><?php if($annotation['type']!=='pin'):?><div><?php echo nl2br(esc_html($annotation['text'])); ?></div><?php endif;?></article><?php endforeach; ?>
 <div class="gmrc-board-context" data-gmrc-board-context hidden><button type="button" data-board-add="note">📝 Add Note</button><button type="button" data-board-add="label">🏷️ Add Label</button><button type="button" data-board-add="pin">📌 Add Pin</button></div><div class="gmrc-board-context" data-gmrc-item-context hidden><button type="button" data-board-action="edit">✏️ Edit</button><button type="button" data-board-action="connect">🧵 Connect with String</button><button type="button" data-board-action="delete">🗑️ Delete from Board</button></div>
 </div>
 <?php if(!$campaign->isArchived()):?><div class="gmrc-conspiracy__actions"><p>Drag by a tack. Right-click empty cork to add a note, label or loose pin. Strings deliberately hang with a little Keeper-grade slack.</p><button type="submit">Save Board Layout</button></div><?php endif;?></form>
<div class="gmrc-board-modal" data-gmrc-board-modal hidden><div class="gmrc-board-modal__veil" data-modal-close></div><section class="gmrc-board-modal__panel" role="dialog" aria-modal="true" aria-labelledby="gmrc-board-modal-title"><button type="button" class="gmrc-board-modal__close" data-modal-close aria-label="Close">×</button><p class="gmrc-dm-desk__eyebrow">Keeper’s Board</p><h2 id="gmrc-board-modal-title" data-modal-heading>Add Note</h2><label>Title<input type="text" data-modal-title maxlength="80" placeholder="The cheese was already melted…"></label><label>Note<textarea data-modal-text rows="5" placeholder="What has the Keeper noticed?"></textarea></label><label>Paper style<select data-modal-style><option value="parchment">Parchment</option><option value="yellow">Yellow note</option><option value="scrap">Torn scrap</option><option value="warning">Warning</option></select></label><div class="gmrc-board-modal__actions"><button type="button" data-modal-close>Cancel</button><button type="button" data-modal-save>Pin to Board</button></div></section></div><div class="gmrc-board-modal" data-gmrc-delete-modal hidden><div class="gmrc-board-modal__veil" data-delete-close></div><section class="gmrc-board-modal__panel" role="dialog" aria-modal="true"><p class="gmrc-dm-desk__eyebrow">Remove Board Item</p><h2>Take this off the board?</h2><p>This removes only the board note, label or loose pin. Canonical campaign records are never deleted here.</p><div class="gmrc-board-modal__actions"><button type="button" data-delete-close>Keep It</button><button type="button" data-delete-confirm>Remove from Board</button></div></section></div></section>
