<?php

declare(strict_types=1);

namespace GreatMarketrealmCompanion\Modules\Characters\Arcana\Models;

use GreatMarketrealmCompanion\Modules\Characters\Arcana\Services\StewardSpellAbilityBridge;

defined('ABSPATH') || exit;

/**
 * Phase III.5 spell and feature catalogue.
 */
final class ArcaneAbilityCatalogue
{
    /** @var ArcaneAbilityDefinition[] */
    private array $abilities;

    public function __construct()
    {
        $this->abilities = [
            new ArcaneAbilityDefinition(
                'produce-spark',
                'Produce Spark',
                'cantrip',
                ['wizard', 'sorcerer', 'artificer'],
                'A bright seed of market-light streaks toward one creature.',
                '1 action',
                '60 ft',
                'Instantaneous',
                'At will',
                'damage',
                '1d10',
                'radiant',
                null,
                false,
                true,
                characterLevelScaling: [
                    1 => '1d10',
                    5 => '2d10',
                    11 => '3d10',
                    17 => '4d10',
                ]
            ),
            new ArcaneAbilityDefinition(
                'vine-lash',
                'Vine Lash',
                'cantrip',
                ['druid'],
                'A spectral vine snaps from your palm and catches a nearby foe.',
                '1 action',
                '30 ft',
                'Instantaneous',
                'At will',
                'damage',
                '1d6',
                'piercing',
                null,
                false,
                true,
                characterLevelScaling: [
                    1 => '1d6',
                    5 => '2d6',
                    11 => '3d6',
                    17 => '4d6',
                ]
            ),
            new ArcaneAbilityDefinition(
                'bureaucratic-hex',
                'Bureaucratic Hex',
                'cantrip',
                ['warlock'],
                'A stamped sigil of impossible paperwork strikes with eldritch force.',
                '1 action',
                '120 ft',
                'Instantaneous',
                'At will',
                'damage',
                '1d10',
                'force',
                null,
                false,
                true,
                characterLevelScaling: [
                    1 => '1d10',
                    5 => '2d10',
                    11 => '3d10',
                    17 => '4d10',
                ]
            ),
            new ArcaneAbilityDefinition(
                'cutting-remark',
                'Cutting Remark',
                'cantrip',
                ['bard'],
                'A devastating observation attacks the confidence of one creature.',
                '1 action',
                '60 ft',
                'Instantaneous',
                'At will',
                'damage',
                '1d6',
                'psychic',
                'wisdom',
                characterLevelScaling: [
                    1 => '1d6',
                    5 => '2d6',
                    11 => '3d6',
                    17 => '4d6',
                ]
            ),
            new ArcaneAbilityDefinition(
                'sacred-brine',
                'Sacred Brine',
                'cantrip',
                ['cleric'],
                'A silver splash of sanctified brine burns spoilage and wickedness.',
                '1 action',
                '60 ft',
                'Instantaneous',
                'At will',
                'damage',
                '1d8',
                'radiant',
                'dexterity',
                characterLevelScaling: [
                    1 => '1d8',
                    5 => '2d8',
                    11 => '3d8',
                    17 => '4d8',
                ]
            ),
            new ArcaneAbilityDefinition(
                'restorative-preserve',
                'Restorative Preserve',
                'spell',
                ['bard', 'cleric', 'druid', 'artificer'],
                'Warm berry preserve seals cuts and restores an adventurer’s vigour.',
                '1 action',
                'Touch',
                'Instantaneous',
                '1st-level slot',
                'healing',
                '1d8',
                null,
                null,
                true,
                spellLevel: 1,
                slotLevelScaling: [
                    1 => '1d8',
                    2 => '2d8',
                    3 => '3d8',
                    4 => '4d8',
                    5 => '5d8',
                    6 => '6d8',
                    7 => '7d8',
                    8 => '8d8',
                    9 => '9d8',
                ]
            ),
            new ArcaneAbilityDefinition(
                'pantry-ward',
                'Pantry Ward',
                'spell',
                ['wizard', 'artificer'],
                'A translucent pantry-door sigil briefly protects a creature from harm.',
                '1 reaction',
                'Self',
                '1 round',
                '1st-level slot',
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'market-missile',
                'Market Missile',
                'spell',
                ['wizard', 'sorcerer'],
                'Three glowing price-tags unerringly streak toward creatures you can see.',
                '1 action',
                '120 ft',
                'Instantaneous',
                '1st-level slot',
                'damage',
                '3d4',
                'force',
                spellLevel: 1,
                slotLevelScaling: [
                    1 => '3d4',
                    2 => '4d4',
                    3 => '5d4',
                    4 => '6d4',
                    5 => '7d4',
                    6 => '8d4',
                    7 => '9d4',
                    8 => '10d4',
                    9 => '11d4',
                ]
            ),
            new ArcaneAbilityDefinition(
                'receipt-shield',
                'Receipt Shield',
                'spell',
                ['wizard'],
                'A fluttering ribbon of enchanted receipts snaps into a warding barrier.',
                '1 reaction',
                'Self',
                '1 round',
                '1st-level slot',
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'crate-bolt',
                'Crate Bolt',
                'spell',
                ['wizard', 'sorcerer'],
                'A splintering bolt of spectral packing-crate wood slams into one creature.',
                '1 action',
                '90 ft',
                'Instantaneous',
                '1st-level slot',
                'damage',
                '1d8',
                'force',
                null,
                false,
                true,
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'label-snare',
                'Label Snare',
                'spell',
                ['wizard'],
                'Animated price labels twist around a creature and try to pin it in place.',
                '1 action',
                '60 ft',
                'Concentration, up to 1 minute',
                '1st-level slot',
                null,
                null,
                null,
                'strength',
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'shelfshine',
                'Shelfshine',
                'cantrip',
                ['wizard', 'sorcerer', 'cleric', 'bard', 'artificer'],
                'You touch one object and make it shine with neat enchanted shelf-light.',
                '1 action',
                'Touch',
                '1 hour',
                'At will'
            ),
            new ArcaneAbilityDefinition(
                'shelf-alarm',
                'Shelf Alarm',
                'spell',
                ['wizard'],
                'Mark a doorway, shelf or container with a quiet magical inventory alarm.',
                '1 minute',
                '30 ft',
                '8 hours',
                '1st-level slot',
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'paper-cut-swarm',
                'Paper Cut Swarm',
                'spell',
                ['wizard'],
                'A storm of razor-edged inventory slips whirls through a tightly packed space.',
                '1 action',
                '60 ft',
                'Instantaneous',
                '1st-level slot',
                'damage',
                '2d4',
                'slashing',
                'dexterity',
                spellLevel: 1
            ),
            new ArcaneAbilityDefinition(
                'aisle-step',
                'Aisle Step',
                'spell',
                ['wizard', 'sorcerer'],
                'Fold the space between two shelves and reappear at an unoccupied spot you can see.',
                '1 bonus action',
                'Self',
                'Instantaneous',
                '2nd-level slot',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'stockroom-veil',
                'Stockroom Veil',
                'spell',
                ['wizard'],
                'Wrap yourself in the dim hush of a forgotten stockroom, blurring your outline from hostile eyes.',
                '1 action',
                'Self',
                'Concentration, up to 1 hour',
                '2nd-level slot',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'price-freeze',
                'Price Freeze',
                'spell',
                ['wizard', 'artificer'],
                'A crystalline price-label snaps into place and momentarily arrests one creature’s movement.',
                '1 action',
                '60 ft',
                'Concentration, up to 1 minute',
                '2nd-level slot',
                null,
                null,
                null,
                'wisdom',
                false,
                false,
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'crate-levitation',
                'Crate Levitation',
                'spell',
                ['wizard', 'artificer'],
                'Invisible stockroom hands lift a creature or heavy parcel gently into the air.',
                '1 action',
                '60 ft',
                'Concentration, up to 10 minutes',
                '2nd-level slot',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'forklift-hand',
                'Forklift Hand',
                'spell',
                ['wizard', 'artificer'],
                'A translucent lifting fork of force moves an unattended crate or object through the air.',
                '1 action',
                '60 ft',
                'Concentration, up to 10 minutes',
                '2nd-level slot',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'cold-aisle-shard',
                'Cold Aisle Shard',
                'spell',
                ['wizard', 'sorcerer'],
                'A jagged shard of freezer-aisle frost streaks toward a creature and bursts on impact.',
                '1 action',
                '90 ft',
                'Instantaneous',
                '2nd-level slot',
                'damage',
                '3d6',
                'cold',
                null,
                false,
                true,
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'inventory-mirage',
                'Inventory Mirage',
                'spell',
                ['wizard'],
                'Create a convincing illusion of stacked goods, shelving or an empty patch of floor.',
                '1 action',
                '60 ft',
                'Concentration, up to 10 minutes',
                '2nd-level slot',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'barcode-bind',
                'Barcode Bind',
                'spell',
                ['wizard'],
                'Bands of luminous barcode-lines wrap around a creature and tighten when it struggles.',
                '1 action',
                '60 ft',
                'Concentration, up to 1 minute',
                '2nd-level slot',
                null,
                null,
                null,
                'strength',
                spellLevel: 2
            ),
            new ArcaneAbilityDefinition(
                'aisle-lightning',
                'Aisle Lightning',
                'spell',
                ['wizard', 'sorcerer'],
                'A crackling bolt races in a straight line down the aisle, scorching everything in its path.',
                '1 action',
                '100 ft line',
                'Instantaneous',
                '3rd-level slot',
                'damage',
                '8d6',
                'lightning',
                'dexterity',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'stockroom-fireball',
                'Stockroom Fireball',
                'spell',
                ['wizard', 'sorcerer'],
                'A bead of compressed stockroom heat blossoms into a roaring sphere of flame.',
                '1 action',
                '150 ft',
                'Instantaneous',
                '3rd-level slot',
                'damage',
                '8d6',
                'fire',
                'dexterity',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'sealed-delivery',
                'Sealed Delivery',
                'spell',
                ['wizard'],
                'Fold a small parcel into a temporary pocket of market-space for safe transport.',
                '1 action',
                'Touch',
                '8 hours',
                '3rd-level slot',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'closing-time-haste',
                'Closing Time Haste',
                'spell',
                ['wizard'],
                'Urgent closing-time magic quickens one creature into a blur of impossible efficiency.',
                '1 action',
                '30 ft',
                'Concentration, up to 1 minute',
                '3rd-level slot',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'frozen-stock',
                'Frozen Stock',
                'spell',
                ['wizard'],
                'Flash-freeze a patch of ground and anything carelessly standing upon it.',
                '1 action',
                '90 ft',
                'Concentration, up to 1 minute',
                '3rd-level slot',
                'damage',
                '4d6',
                'cold',
                'dexterity',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'grand-relabel',
                'Grand Relabel',
                'spell',
                ['wizard'],
                'Temporarily rewrite the apparent markings, signs and identifying labels across a small area.',
                '1 action',
                '60 ft',
                '1 hour',
                '3rd-level slot',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'pallet-wall',
                'Pallet Wall',
                'spell',
                ['wizard'],
                'Interlocking spectral pallets rise into a sturdy temporary barrier.',
                '1 action',
                '60 ft',
                'Concentration, up to 10 minutes',
                '3rd-level slot',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'return-to-sender',
                'Return to Sender',
                'spell',
                ['wizard'],
                'A snap of reverse-delivery magic hurls one nearby creature away from you.',
                '1 action',
                '30 ft',
                'Instantaneous',
                '3rd-level slot',
                'damage',
                '4d8',
                'force',
                'strength',
                spellLevel: 3
            ),
            new ArcaneAbilityDefinition(
                'fresh-stock',
                'Fresh Stock',
                'feature',
                ['grocer'],
                'Your eye for quality lets you identify useful provisions and keep the party supplied.',
                '1 minute',
                'Nearby goods',
                'Instantaneous',
                'At will'
            ),
            new ArcaneAbilityDefinition(
                'emergency-restock',
                'Emergency Restock',
                'feature',
                ['grocer'],
                'Produce exactly the snack somebody swore was packed earlier.',
                '1 bonus action',
                '30 ft',
                'Instantaneous',
                'Once per long rest',
                'healing',
                '1d6',
                null,
                null,
                true
            ),
            new ArcaneAbilityDefinition(
                'sacred-wrapping',
                'Sacred Wrapping',
                'feature',
                ['cleaver-saint'],
                'Ceremonial wrapping steadies your resolve against rot and corruption.',
                '1 bonus action',
                'Self',
                '1 minute',
                'Once per long rest'
            ),
            new ArcaneAbilityDefinition(
                'second-wind',
                'Second Wind',
                'feature',
                ['fighter'],
                'Catch your breath and pull yourself back into the fight.',
                '1 bonus action',
                'Self',
                'Instantaneous',
                'Once per short rest',
                'healing',
                '1d10',
                null,
                null,
                true
            ),
            new ArcaneAbilityDefinition(
                'rage',
                'Rage',
                'feature',
                ['barbarian'],
                'Channel a furious market-day determination into battle.',
                '1 bonus action',
                'Self',
                '1 minute',
                'Twice per long rest'
            ),
            new ArcaneAbilityDefinition(
                'sneak-attack',
                'Sneak Attack',
                'feature',
                ['rogue'],
                'Exploit a distracted foe for an extra burst of precision damage.',
                'On hit',
                'Weapon range',
                'Instantaneous',
                'Once per turn',
                'damage',
                '1d6',
                'weapon',
                characterLevelScaling: [
                    1 => '1d6',
                    3 => '2d6',
                    5 => '3d6',
                    7 => '4d6',
                    9 => '5d6',
                    11 => '6d6',
                    13 => '7d6',
                    15 => '8d6',
                    17 => '9d6',
                    19 => '10d6',
                ]
            ),
            new ArcaneAbilityDefinition(
                'martial-arts',
                'Martial Arts',
                'feature',
                ['monk'],
                'Your disciplined strikes turn ordinary limbs into adventuring implements.',
                'On attack',
                'Melee',
                'Instantaneous',
                'At will',
                'damage',
                '1d4',
                'bludgeoning',
                characterLevelScaling: [
                    1 => '1d4',
                    5 => '1d6',
                    11 => '1d8',
                    17 => '1d10',
                ]
            ),
            new ArcaneAbilityDefinition(
                'divine-sense',
                'Divine Sense',
                'feature',
                ['paladin'],
                'Sense strongly spoiled, sacred or profane presences nearby.',
                '1 action',
                '60 ft',
                '1 round',
                'Limited uses'
            ),
            new ArcaneAbilityDefinition(
                'favoured-mark',
                'Favoured Mark',
                'feature',
                ['ranger'],
                'Study a quarry and mark the signs needed to track it through the Marketrealm.',
                '1 bonus action',
                '90 ft',
                '1 hour',
                'Limited uses'
            ),
            new ArcaneAbilityDefinition(
                'pantry-recovery', 'Pantry Recovery', 'feature', ['wizard'],
                'During a short rest, reorganise the Arcane Pantry and recover a little spent magical stock.',
                'Short rest', 'Self', 'Instantaneous', 'Once per long rest',
                null, null, null, null, false, false, 2
            ),
            new ArcaneAbilityDefinition(
                'stocktake-instinct', 'Stocktake Instinct', 'feature', ['grocer'],
                'A rapid stocktake reveals overlooked supplies, suspicious substitutions and hidden value.',
                '1 action', '30 ft', 'Instantaneous', 'Proficiency bonus per long rest',
                null, null, null, null, false, false, 2
            ),
            new ArcaneAbilityDefinition(
                'action-surge', 'Action Surge', 'feature', ['fighter'],
                'Dig deep and take one additional action on your turn.',
                'Free', 'Self', 'Instantaneous', 'Once per short rest',
                null, null, null, null, false, false, 2
            ),
            new ArcaneAbilityDefinition(
                'sanctified-slice', 'Sanctified Slice', 'feature', ['cleaver-saint'],
                'Consecrate a strike with a ribbon of brilliant preserving light.',
                'On hit', 'Weapon range', 'Instantaneous', 'Once per long rest',
                'damage', '1d8', 'radiant', null, false, false, 2
            ),
        ];

        $this->abilities = array_merge(
            $this->abilities,
            (new StewardSpellAbilityBridge())->abilities()
        );
    }

    /** @return ArcaneAbilityDefinition[] */
    public function forClass(string $class): array
    {
        return array_values(
            array_filter(
                $this->abilities,
                static fn (ArcaneAbilityDefinition $ability): bool =>
                    $ability->supportsClass($class)
            )
        );
    }
}
