<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Tests\Unit\Modules\DungeonMaster;
use PHPUnit\Framework\TestCase;
final class CampaignJournalRegressionTest extends TestCase
{
 public function testJournalRoutesAndDedicatedControllerExist(): void{$r=$this->source('app/Modules/DungeonMaster/Routes.php');self::assertStringContainsString("'/dungeon-master/campaigns/{id}/journal'",$r);self::assertStringContainsString('JournalController::class',$r);self::assertStringContainsString("'/archive'",$r);}
 public function testJournalPersistenceIsPrivateAndCampaignOwnerScoped(): void{$r=$this->source('app/Modules/DungeonMaster/Repositories/JournalRepository.php');self::assertStringContainsString("public const POST_TYPE='gmrc_dm_journal'",$r);self::assertStringContainsString("'author'=>$campaign->ownerId()",$r);self::assertStringContainsString("META_CAMPAIGN",$r);self::assertStringContainsString("'public'=>false",$this->source('app/Modules/DungeonMaster/DungeonMasterServiceProvider.php'));}
 public function testJournalModelSupportsUsefulDmClassifications(): void{$m=$this->source('app/Modules/DungeonMaster/Models/JournalEntry.php');foreach(['npc','location','plot-thread','secret','lore','treasure','faction'] as $category){self::assertStringContainsString("'{$category}'",$m);}self::assertStringContainsString("['active','resolved','archived']",$m);self::assertStringContainsString('pinned',strtolower($m));}
 public function testJournalCanLinkOnlyToSessionInsideCampaign(): void{$c=$this->source('app/Modules/DungeonMaster/Controllers/JournalController.php');self::assertStringContainsString('validSessionId',$c);self::assertStringContainsString('findForCampaign($sessionId,$campaign)',$this->compact($c));self::assertStringContainsString('does not belong to this Campaign',$c);}
 public function testArchivedCampaignJournalIsReadOnly(): void{$c=$this->source('app/Modules/DungeonMaster/Controllers/JournalController.php');self::assertStringContainsString('assertActive',$c);self::assertStringContainsString('read-only Campaign Journal',$c);}
 public function testJournalUsesExistingDmCapabilityAndDedicatedNonce(): void{$q=$this->source('app/Modules/DungeonMaster/Requests/SaveJournalEntryRequest.php');$f=$this->source('app/Modules/DungeonMaster/Views/journal/_form.php');self::assertStringContainsString("current_user_can('gmrc_manage_campaigns')",$q);self::assertStringContainsString("gmrc_dm_journal_",$f);}
 public function testJournalViewsExposePrivateNotesAndSessionRelationship(): void{$i=$this->source('app/Modules/DungeonMaster/Views/journal/index.php');$f=$this->source('app/Modules/DungeonMaster/Views/journal/_form.php');self::assertStringContainsString('Private DM Chronicle',$i);self::assertStringContainsString('Related Session',$f);self::assertStringContainsString('Private Dungeon Master notes',$f);}
 public function testJournalIsLinkedFromCampaignAndDmDesk(): void{$campaign=$this->source('app/Modules/DungeonMaster/Views/campaigns/show.php');$desk=$this->source('app/Modules/DungeonMaster/Views/index.php');self::assertStringContainsString('Open Campaign Journal',$campaign);self::assertStringContainsString('Ledger VI · Open',$desk);self::assertStringContainsString('Campaign Journal',$desk);}
 public function testJournalVisualTreatmentStaysInsideContentWorkspace(): void{$css=$this->source('assets/css/modules/dungeon-master/campaign-journal.css');self::assertStringContainsString('.gmrc-content:has(> .gmrc-campaign-journal)',$css);self::assertStringNotContainsString('.gmrc-app-main:has',$css);self::assertStringContainsString('prefers-reduced-transparency',$css);self::assertStringContainsString('forced-colors:active',$this->compact($css));self::assertStringContainsString('@supports not',$css);}
 public function testJournalStylesAreActuallyEnqueued(): void{$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("'handle' => 'gmrc-campaign-journal'",$provider);self::assertStringContainsString("modules/dungeon-master/campaign-journal.css",$provider);}
 private function source(string $relative): string{$source=file_get_contents($this->root().'/'.$relative);self::assertIsString($source);return $source;} private function compact(string $source): string{return preg_replace('/\\s+/','',$source)??$source;} private function root(): string{return dirname(__DIR__,4);}
}
