<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Tests\Unit\Modules\DungeonMaster;
use PHPUnit\Framework\TestCase;
final class ConspiracyBoardRegressionTest extends TestCase
{
 public function testBoardIsCampaignScopedAndUsesCanonicalRegisters():void{$controller=$this->source('app/Modules/DungeonMaster/Controllers/ConspiracyBoardController.php');self::assertStringContainsString('LocationRepository',$controller);self::assertStringContainsString('PersonaRepository',$controller);self::assertStringContainsString('EvidenceRepository',$controller);self::assertStringContainsString("'/dungeon-master/campaigns/{id}/conspiracy-board'",$this->source('app/Modules/DungeonMaster/Routes.php'));}
 public function testBoardStoresOnlyPresentationPositionsOnCampaign():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_positions',$repo);self::assertStringNotContainsString('post_title',$repo);self::assertStringNotContainsString('wp_insert_post',$repo);}
 public function testCampaignCommandCentreOpensBoard():void{$view=$this->source('app/Modules/DungeonMaster/Views/campaigns/show.php');self::assertStringContainsString("\$campaignPath . '/conspiracy-board'",$view);self::assertStringContainsString('Open Conspiracy Board',$view);}
 public function testBoardPresentationHasPinsStringsAndNoVisiblePhaseNumber():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString('data-gmrc-board-canvas',$view);self::assertStringContainsString('data-gmrc-board-strings',$view);self::assertStringContainsString('Save Board Layout',$view);self::assertStringNotContainsString('III.17.5',$view);}
 public function testGatewayRecognisesBoardNonce():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("wp_create_nonce('gmrc_dm_conspiracy_board_",$view);self::assertStringContainsString("str_ends_with(\$gmrcRoute, '/conspiracy-board')",$provider);}
 public function testBoardCanPersistBoardOnlyAnnotations():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_annotations',$repo);self::assertStringContainsString('saveAnnotations',$repo);self::assertStringContainsString("['pin','note','label','image']",$repo);}
 public function testBoardOffersRightClickPinsNotesAndLabels():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-gmrc-board-context',$view);self::assertStringContainsString('data-board-add="note"',$view);self::assertStringContainsString('data-board-add="label"',$view);self::assertStringContainsString('data-board-add="pin"',$view);self::assertStringContainsString("addEventListener('contextmenu'",$script);}
 public function testStringsUseSlackPathsAndBoardUsesMoreViewport():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString("createElementNS('http://www.w3.org/2000/svg','path')",$script);self::assertStringContainsString(' Q ${mx} ${my} ', $script);self::assertStringContainsString('width:min(96vw,1680px)',str_replace(' ','',$css));self::assertStringContainsString('78vh',$css);}
 public function testBoardPersistsManualKeeperStrings():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_connections',$repo);self::assertStringContainsString('saveConnections',$repo);self::assertStringContainsString('manual_connections',$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php'));}
 public function testBoardUsesKeeperModalAndDeleteControls():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString('data-gmrc-board-modal',$view);self::assertStringContainsString('data-gmrc-delete-modal',$view);self::assertStringContainsString('Connect with String',$view);self::assertStringContainsString('Delete from Board',$view);}
 public function testBoardLegendActsAsToggleFilters():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-board-filter="location"',$view);self::assertStringContainsString('aria-pressed="false"',$view);self::assertStringContainsString('applyFilters',$script);}
 public function testWorkshopPagesShareDungeonMasterBackdropAndStringsBounce():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('dungeon-master-desk-background.png',$css);self::assertStringContainsString('animateBounce',$script);self::assertStringContainsString('requestAnimationFrame(animateBounce)',$script);}
 public function testBoardKeepsAnnotationsInsideCorkAndFooterInOneFrame():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function clampItem',$script);self::assertStringContainsString('allItems().forEach(clampItem)',$script);self::assertStringContainsString('.gmrc-conspiracy__form{overflow:visible;background:#3a2114;padding:12px',$css);self::assertStringContainsString('.gmrc-board-annotation--pin.gmrc-board-annotation--scrap',$css);}
 public function testTornScrapKeepsItsTackAtTopCentre():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString('.gmrc-board-annotation--scrap > .gmrc-board-annotation__tack',$css);self::assertStringContainsString('left:50%!important',$css);self::assertStringContainsString('transform:translateX(-50%)!important',$css);}
 public function testAnnotationPresentationSurvivesSaveRoundTrip():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString("'title'=>sanitize_text_field",$repo);self::assertStringContainsString("'style'=>\$this->style",$repo);self::assertStringContainsString("'image_id'=>absint",$repo);}
 public function testBoardCanPinAndRemoveCanonicalCampaignRecords():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('data-board-record="location"',$view);self::assertStringContainsString('Add Clue / Evidence',$view);self::assertStringContainsString('_gmrc_conspiracy_board_hidden_records',$repo);}
 public function testBoardSupportsPinnedImagesThroughWordPressMedia():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString('data-board-add="image"',$view);self::assertStringContainsString('data-gmrc-image-modal',$view);self::assertStringContainsString('wp_enqueue_media()',$provider);}
 public function testBoardHasZoomFitAndScrollableViewport():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-board-zoom-in',$view);self::assertStringContainsString('data-board-zoom-out',$view);self::assertStringContainsString('data-board-zoom-fit',$view);self::assertStringContainsString('function setZoom',$script);}
 public function testConspiracyBoardAssetsAndMediaAreEnqueued():void{$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("'handle' => 'gmrc-conspiracy-board'",$provider);self::assertStringContainsString("'path' => 'modules/dungeon-master/conspiracy-board.css'",$provider);self::assertStringContainsString('assets/js/modules/dungeon-master/conspiracy-board.js',$provider);self::assertStringContainsString('wp_enqueue_media()',$provider);}
 public function testBoardSaveNonceMatchesApplicationGatewayContract():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString('name="action" value="gmrc_app_request"',$view);self::assertStringContainsString("wp_create_nonce('gmrc_dm_conspiracy_board_",$view);self::assertStringContainsString("#^dungeon-master/campaigns/([^/]+)/conspiracy-board$#",$provider);self::assertStringContainsString("return 'gmrc_dm_conspiracy_board_'",$provider);}
 public function testTornPaperDoesNotClipItsPhysicalTack():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString('.gmrc-board-annotation--scrap:not(.gmrc-board-annotation--pin)::before',$css);self::assertStringContainsString('clip-path:none',$css);self::assertStringContainsString('>.gmrc-board-annotation__tack{z-index:7}',$css);}
 public function testNormalBoardDoesNotUseInternalScrollAndFitUsesBothAxes():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('.gmrc-conspiracy__viewport{overflow:visible;max-height:none',$css);self::assertStringContainsString('.gmrc-conspiracy__viewport.is-board-zoomed{overflow:auto',$css);self::assertStringContainsString('availableWidth/boardWidth,availableHeight/boardHeight',$script);self::assertStringContainsString('min-height:max(920px,84vh)',$css);}
 private function source(string $path):string{$source=file_get_contents(dirname(__DIR__,4).'/'.$path);self::assertIsString($source);return $source;}
}
