<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Tests\Unit\Modules\DungeonMaster;
use PHPUnit\Framework\TestCase;
final class ConspiracyBoardRegressionTest extends TestCase
{
 public function testBoardIsCampaignScopedAndUsesCanonicalRegisters():void{$controller=$this->source('app/Modules/DungeonMaster/Controllers/ConspiracyBoardController.php');self::assertStringContainsString('LocationRepository',$controller);self::assertStringContainsString('PersonaRepository',$controller);self::assertStringContainsString('EvidenceRepository',$controller);self::assertStringContainsString("'/dungeon-master/campaigns/{id}/conspiracy-board'",$this->source('app/Modules/DungeonMaster/Routes.php'));}
 public function testBoardStoresOnlyPresentationPositionsOnCampaign():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_positions',$repo);self::assertStringNotContainsString('post_title',$repo);self::assertStringNotContainsString('wp_insert_post',$repo);}
 public function testCampaignCommandCentreOpensBoard():void{$view=$this->source('app/Modules/DungeonMaster/Views/campaigns/show.php');self::assertStringContainsString("\$campaignPath . '/conspiracy-board'",$view);self::assertStringContainsString('Open Conspiracy Board',$view);}
 public function testBoardPresentationHasPinsStringsAndNoVisiblePhaseNumber():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString('data-gmrc-board-canvas',$view);self::assertStringContainsString('data-gmrc-board-strings',$view);self::assertStringContainsString('Save Board Layout',$view);self::assertStringNotContainsString('III.17.5',$view);}
 public function testGatewayRecognisesBoardNonce():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("wp_create_nonce('gmrc_dm_conspiracy_board_",$view);self::assertStringContainsString("str_ends_with(\$gmrcRoute, '/conspiracy-board')",$provider);}
 public function testBoardCanPersistBoardOnlyAnnotations():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_annotations',$repo);self::assertStringContainsString('saveAnnotations',$repo);self::assertStringContainsString("['pin','note','label','image']",$repo);}
 public function testBoardOffersRightClickPinsNotesAndLabels():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-gmrc-board-context',$view);self::assertStringContainsString('data-board-add="note"',$view);self::assertStringContainsString('data-board-add="label"',$view);self::assertStringContainsString('data-board-add="pin"',$view);self::assertStringContainsString("addEventListener('contextmenu'",$script);}
 public function testStringsUseSlackPathsAndBoardUsesMoreViewport():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString("createElementNS('http://www.w3.org/2000/svg','path')",$script);self::assertStringContainsString(' Q ${mx} ${my} ', $script);self::assertStringContainsString('width:min(96vw,1680px)',str_replace(' ','',$css));self::assertStringContainsString('78vh',$css);}
 public function testBoardPersistsManualKeeperStrings():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('_gmrc_conspiracy_board_connections',$repo);self::assertStringContainsString('saveConnections',$repo);self::assertStringContainsString('manual_connections',$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php'));}
 public function testBoardUsesKeeperModalAndDeleteControls():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString('data-gmrc-board-modal',$view);self::assertStringContainsString('data-gmrc-delete-modal',$view);self::assertStringContainsString('Connect with String',$view);self::assertStringContainsString('Delete from Board',$view);}
 public function testBoardLegendActsAsToggleFilters():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-board-filter="location"',$view);self::assertStringContainsString('aria-pressed="false"',$view);self::assertStringContainsString('applyFilters',$script);}
 public function testWorkshopPagesShareDungeonMasterBackdropAndStringsBounce():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('dungeon-master-desk-background.png',$css);self::assertStringContainsString('animateBounce',$script);self::assertStringContainsString('requestAnimationFrame(animateBounce)',$script);}
 public function testBoardKeepsAnnotationsInsideCorkAndFooterInOneFrame():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function clampItem',$script);self::assertStringContainsString('allItems().forEach(clampItem)',$script);self::assertStringContainsString('.gmrc-conspiracy__form{overflow:visible;background:#3a2114;padding:12px',$css);}
 public function testAnnotationPresentationSurvivesSaveRoundTrip():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString("'title'=>sanitize_text_field",$repo);self::assertStringContainsString("'style'=>\$this->style",$repo);self::assertStringContainsString("'image_id'=>absint",$repo);}
 public function testBoardCanPinAndRemoveCanonicalCampaignRecords():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('data-board-record="location"',$view);self::assertStringContainsString('Add Clue / Evidence',$view);self::assertStringContainsString('_gmrc_conspiracy_board_hidden_records',$repo);}
 public function testBoardSupportsPinnedImagesThroughWordPressMedia():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString('data-board-add="image"',$view);self::assertStringContainsString('data-gmrc-image-modal',$view);self::assertStringContainsString('wp_enqueue_media()',$provider);}
 public function testBoardHasZoomFitAndScrollableViewport():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('data-board-zoom-in',$view);self::assertStringContainsString('data-board-zoom-out',$view);self::assertStringContainsString('data-board-zoom-fit',$view);self::assertStringContainsString('function setZoom',$script);}
 public function testConspiracyBoardAssetsAndMediaAreEnqueued():void{$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("'handle' => 'gmrc-conspiracy-board'",$provider);self::assertStringContainsString("'path' => 'modules/dungeon-master/conspiracy-board.css'",$provider);self::assertStringContainsString('assets/js/modules/dungeon-master/conspiracy-board.js',$provider);self::assertStringContainsString('wp_enqueue_media()',$provider);}
 public function testBoardSaveNonceMatchesApplicationGatewayContract():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$provider=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString('name="action" value="gmrc_app_request"',$view);self::assertStringContainsString("wp_create_nonce('gmrc_dm_conspiracy_board_",$view);self::assertStringContainsString("#^dungeon-master/campaigns/([^/]+)/conspiracy-board$#",$provider);self::assertStringContainsString("return 'gmrc_dm_conspiracy_board_'",$provider);}
 public function testNormalBoardDoesNotUseInternalScrollAndFitUsesBothAxes():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('.gmrc-conspiracy__viewport{position:relative;overflow:visible;max-height:none',$css);self::assertStringContainsString('.gmrc-conspiracy__viewport.is-board-zoomed{overflow:auto',$css);self::assertStringContainsString('availableWidth/boardWidth,availableHeight/boardHeight',$script);self::assertStringContainsString('min-height:max(980px,88vh)',$css);}
 public function testRecordAndImageModalsAreIndependentOfNoteModal():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$note=strpos($view,'data-gmrc-board-modal');$noteClose=strpos($view,'</section></div>',$note);$record=strpos($view,'data-gmrc-record-modal');$image=strpos($view,'data-gmrc-image-modal');self::assertIsInt($note);self::assertIsInt($noteClose);self::assertIsInt($record);self::assertIsInt($image);self::assertGreaterThan($noteClose,$record);self::assertGreaterThan($noteClose,$image);}
 public function testRightClickRecordAndImageActionsWireToTheirModals():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('openImageModal()',$script);self::assertStringContainsString('openRecordPicker(b.dataset.boardRecord)',$script);self::assertStringContainsString('imageModal.hidden=false',$script);self::assertStringContainsString('recordModal.hidden=false',$script);}
 public function testRecordPickerOnlyOffersRecordsNotAlreadyOnBoard():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('pins.filter(p=>p.hidden&&p.dataset.boardType===type',$script);self::assertStringContainsString('p.hidden=false',$script);self::assertStringContainsString('hiddenRecords=hiddenRecords.filter',$script);}
 public function testBoardAutoFitsAfterInitialLayout():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function initialiseBoardViewport()',$script);self::assertStringContainsString('captureBoardSize();fitBoard();draw();',$script);self::assertStringContainsString("window.addEventListener('load'",$script);}
 public function testManualStringEndpointsPreserveCanonicalUlidCase():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('private function endpoint(mixed $v):string',$repo);self::assertStringContainsString("preg_replace('/[^A-Za-z0-9_-]/'",$repo);self::assertStringNotContainsString('array_map(\'sanitize_key\',$allowed)',$repo);self::assertStringContainsString('$from=$this->endpoint',$repo);self::assertStringContainsString('$to=$this->endpoint',$repo);}
 public function testRetiredTornScrapsFallBackToParchment():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString("['parchment','yellow','warning']",$repo);self::assertStringNotContainsString('<option value="scrap">',$view);}
 public function testBoardOpensAtFitAndKeepsAnExplicitFitControl():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('captureBoardSize();fitBoard();draw();',$script);self::assertStringContainsString("[data-board-zoom-fit]')?.addEventListener('click',fitBoard)",$script);}
 public function testCanonicalCardPositionsPreserveRecordIdentityCase():void{$repo=$this->source('app/Modules/DungeonMaster/Repositories/ConspiracyBoardRepository.php');self::assertStringContainsString('$k=$this->endpoint($k)',$repo);self::assertStringNotContainsString('$k=sanitize_key((string)$k)',$repo);}
 public function testZoomIsACameraOverOneFixedBoardCoordinateSpace():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString('data-gmrc-board-stage',$view);self::assertStringContainsString('board.style.transform=`scale(${zoom})`',$script);self::assertStringContainsString("stage.style.width=(boardWidth*zoom)+'px'",$script);self::assertStringContainsString('function pointOnBoard(ev)',$script);self::assertStringContainsString('.gmrc-conspiracy__stage{position:relative',$css);self::assertStringNotContainsString("board.style.zoom='1'",$script);}
 public function testZoomedBoardCanPanFromBareCorkWithoutMovingPins():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function canPanFrom(ev)',$script);self::assertStringContainsString("!ev.target.closest('[data-board-key],button,a,path.is-manual",$script);self::assertStringContainsString('viewport.scrollLeft=panStart.left',$script);}
 public function testZoomButtonsUseDeterministicStopsIncludingExactOneHundredPercent():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('const ZOOM_STOPS=[.5,.6,.7,.8,.9,1,1.1,1.25,1.5,1.75]',$script);self::assertStringContainsString('function stepZoom(direction)',$script);self::assertStringContainsString('Math.abs(n-1)<.0001?1:n',$script);}
 public function testFitUsesFixedLogicalBoardDimensionsAndResetsCameraOrigin():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function captureBoardSize()',$script);self::assertStringContainsString("board.style.width=boardWidth+'px'",$script);self::assertStringContainsString("viewport.scrollTo({left:0,top:0})",$script);}
 public function testEstablishedBoardKeepsNewCanonicalRecordsOffBoardUntilPinned():void{$view=$this->source('app/Modules/DungeonMaster/Views/conspiracy-board/index.php');self::assertStringContainsString('$hasBoardLayout=$positions!==[]||$hiddenRecords!==[]||$annotations!==[]',$view);self::assertStringContainsString("\$hasBoardLayout&&!array_key_exists(\$pin['key'],\$positions)",$view);}
 public function testRecordPickerRefreshesCanonicalRegistersBeforeSearching():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function refreshCanonicalPins()',$script);self::assertStringContainsString('fetch(window.location.href',$script);self::assertStringContainsString("doc.querySelectorAll('[data-gmrc-board-canvas] [data-pin-key]')",$script);self::assertStringContainsString('refreshCanonicalPins().finally(render)',$script);}
 public function testUnpinnedCanonicalRecordsRemainHiddenAcrossBoardSaves():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('pins.filter(p=>p.hidden).forEach',$script);self::assertStringContainsString('if(!hiddenRecords.includes(key))hiddenRecords.push(key)',$script);}
 public function testContextMenusLiveInScreenSpaceInsteadOfScaledCork():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString("document.body.appendChild(overlay)",$script);self::assertStringContainsString("overlay.classList.add('gmrc-board-context--screen')",$script);self::assertStringContainsString("itemMenu.style.left=ev.clientX+'px'",$script);self::assertStringContainsString("menu.style.left=ev.clientX+'px'",$script);self::assertStringContainsString('.gmrc-board-context--screen{position:fixed',$css);}
 public function testConnectingFromScreenSpaceMenuStillTargetsLogicalBoardItem():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString("if(action==='connect')startConnect(contextItem)",$script);self::assertStringContainsString("const target=ev.target.closest('[data-board-key]')",$script);self::assertStringContainsString('const to=keyOf(target)',$script);}
 public function testInitialFitWaitsForFinalPageLayout():void{$script=$this->source('assets/js/modules/dungeon-master/conspiracy-board.js');self::assertStringContainsString('function initialiseBoardCamera()',$script);self::assertStringContainsString("if(document.readyState==='complete')initialiseBoardCamera()",$script);self::assertStringContainsString("window.addEventListener('load',initialiseBoardCamera",$script);self::assertStringNotContainsString('captureBoardSize();fitBoard();draw();}requestAnimationFrame',$script);}
 public function testContextMenuKeepsReadableSizeAcrossZoomLevels():void{$css=$this->source('assets/css/modules/dungeon-master/conspiracy-board.css');self::assertStringContainsString('transform:none!important;font-size:16px',$css);}
 private function source(string $path):string{$source=file_get_contents(dirname(__DIR__,4).'/'.$path);self::assertIsString($source);return $source;}
}
