<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Tests\Unit\Modules\DungeonMaster;
use PHPUnit\Framework\TestCase;
final class KeeperGazetteerRegressionTest extends TestCase
{
 public function testGazetteerHasCampaignScopedCrudRoutes():void{$r=$this->source('app/Modules/DungeonMaster/Routes.php');foreach(["'/dungeon-master/campaigns/{id}/locations'","'/dungeon-master/campaigns/{id}/locations/create'","'/dungeon-master/campaigns/{id}/locations/{locationId}'","'/dungeon-master/campaigns/{id}/locations/{locationId}/edit'","'/dungeon-master/campaigns/{id}/locations/{locationId}/archive'"] as $route){self::assertStringContainsString($route,$r);}self::assertStringContainsString('LocationController::class',$r);}
 public function testLocationIsStablePlanningRecordWithHierarchyAndVisibility():void{$m=$this->source('app/Modules/DungeonMaster/Models/Location.php');foreach(['parentId','visibility','tabletopSceneId','keeper','players'] as $term){self::assertStringContainsString($term,$m);}self::assertStringContainsString('Ulid::generate()',$m);}
 public function testRepositoryIsPrivateOwnerAndCampaignScoped():void{$r=$this->source('app/Modules/DungeonMaster/Repositories/LocationRepository.php');self::assertStringContainsString("public const POST_TYPE='gmrc_dm_location'",$r);self::assertStringContainsString("'author'=>\$campaign->ownerId()",$r);self::assertStringContainsString('META_CAMPAIGN',$r);self::assertStringContainsString('META_TABLETOP_SCENE',$r);$p=$this->source('app/Modules/DungeonMaster/DungeonMasterServiceProvider.php');self::assertStringContainsString('LocationRepository::POST_TYPE',$p);self::assertStringContainsString("'public'=>false",$p);}
 public function testControllerProtectsTreeIntegrityAndArchivedCampaigns():void{$c=$this->source('app/Modules/DungeonMaster/Controllers/LocationController.php');self::assertStringContainsString('validParentId',$c);self::assertStringContainsString('cannot contain itself',$c);self::assertStringContainsString('circular Gazetteer location tree',$c);self::assertStringContainsString('read-only Keeper’s Gazetteer',$c);self::assertStringContainsString('child places before archiving',$c);}
 public function testGazetteerUsesDmCapabilityAndDedicatedNonce():void{$q=$this->source('app/Modules/DungeonMaster/Requests/SaveLocationRequest.php');$f=$this->source('app/Modules/DungeonMaster/Views/locations/_form.php');self::assertStringContainsString("current_user_can('gmrc_manage_campaigns')",$q);self::assertStringContainsString('gmrc_dm_gazetteer_',$f);}
 public function testGazetteerExposesFutureCartographerSeamWithoutOwningScene():void{$f=$this->source('app/Modules/DungeonMaster/Views/locations/_form.php');$s=$this->source('app/Modules/DungeonMaster/Views/locations/show.php');self::assertStringContainsString('canonical campaign record',$f);self::assertStringContainsString('Cartographer’s Bench',$s);self::assertStringContainsString('future GMRT Cartographer bridge',$s);}
 public function testWorkshopAndCampaignNowOpenTheGazetteer():void{$w=$this->source('app/Modules/DungeonMaster/Services/KeeperWorkspace.php');$d=$this->source('app/Modules/DungeonMaster/Views/index.php');$c=$this->source('app/Modules/DungeonMaster/Views/campaigns/show.php');self::assertStringContainsString("'status' => 'open'",$w);self::assertStringContainsString('Your Campaigns',$d);self::assertStringNotContainsString('Choose Campaign',$d);self::assertStringContainsString('Open Keeper’s Gazetteer',$c);}
 public function testGazetteerStylesAreResponsiveAccessibleAndEnqueued():void{$css=$this->source('assets/css/modules/dungeon-master/keeper-gazetteer.css');self::assertStringContainsString('@media(max-width:760px)',$this->compact($css));self::assertStringContainsString('prefers-reduced-transparency',$css);self::assertStringContainsString('forced-colors:active',$this->compact($css));self::assertStringContainsString('@supports not',$css);$p=$this->source('app/Providers/FrontendServiceProvider.php');self::assertStringContainsString("'handle' => 'gmrc-keeper-gazetteer'",$p);self::assertStringContainsString('modules/dungeon-master/keeper-gazetteer.css',$p);}
 private function source(string $relative):string{$source=file_get_contents($this->root().'/'.$relative);self::assertIsString($source);return $source;}private function compact(string $source):string{return preg_replace('/\\s+/','',$source)??$source;}private function root():string{return dirname(__DIR__,4);}
}
