<?php
declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use RuntimeException;
defined('ABSPATH') || exit;
final class ConspiracyBoardRepository{
 private const META_POSITIONS='_gmrc_conspiracy_board_positions',META_ANNOTATIONS='_gmrc_conspiracy_board_annotations',META_CONNECTIONS='_gmrc_conspiracy_board_connections',META_HIDDEN_RECORDS='_gmrc_conspiracy_board_hidden_records';
 public function __construct(private CampaignRepository $campaigns){}
 public function positions(Campaign $c):array{$d=$this->decoded($c,self::META_POSITIONS);$o=[];foreach($d as $k=>$v)if(is_string($k)&&is_array($v))$o[$k]=['x'=>$this->pct($v['x']??0),'y'=>$this->pct($v['y']??0),'width'=>$this->dimension($v['width']??0,160,720),'height'=>$this->dimension($v['height']??0,90,720),'angle'=>$this->angle($v['angle']??0)];return$o;}
 public function savePositions(Campaign $c,array $a):void{$o=[];foreach($a as $k=>$v){$k=$this->endpoint($k);if($k!==''&&is_array($v))$o[$k]=['x'=>$this->pct($v['x']??0),'y'=>$this->pct($v['y']??0),'width'=>$this->dimension($v['width']??0,160,720),'height'=>$this->dimension($v['height']??0,90,720),'angle'=>$this->angle($v['angle']??0)];}$this->save($c,self::META_POSITIONS,$o);}
 public function annotations(Campaign $c):array{$o=[];foreach($this->decoded($c,self::META_ANNOTATIONS) as $v){if(!is_array($v))continue;$id=sanitize_key((string)($v['id']??''));$type=sanitize_key((string)($v['type']??''));if($id===''||!in_array($type,['pin','note','label','image'],true))continue;$style=$this->style($v['style']??'parchment');$o[]=['id'=>$id,'type'=>$type,'title'=>sanitize_text_field((string)($v['title']??'')),'text'=>sanitize_textarea_field((string)($v['text']??'')),'style'=>$style,'image_id'=>absint($v['image_id']??0),'image_url'=>esc_url_raw((string)($v['image_url']??'')),'width'=>$this->dimension($v['width']??0,160,720),'height'=>$this->dimension($v['height']??0,90,720),'angle'=>$this->angle($v['angle']??0),'x'=>$this->pct($v['x']??0),'y'=>$this->pct($v['y']??0)];}return$o;}
 public function saveAnnotations(Campaign $c,array $a):void{$o=[];foreach($a as $v){if(!is_array($v))continue;$id=sanitize_key((string)($v['id']??''));$type=sanitize_key((string)($v['type']??''));if($id===''||!in_array($type,['pin','note','label','image'],true))continue;$o[]=['id'=>$id,'type'=>$type,'title'=>sanitize_text_field((string)($v['title']??'')),'text'=>sanitize_textarea_field((string)($v['text']??'')),'style'=>$this->style($v['style']??'parchment'),'image_id'=>absint($v['image_id']??0),'image_url'=>esc_url_raw((string)($v['image_url']??'')),'width'=>$this->dimension($v['width']??0,160,720),'height'=>$this->dimension($v['height']??0,90,720),'angle'=>$this->angle($v['angle']??0),'x'=>$this->pct($v['x']??0),'y'=>$this->pct($v['y']??0)];}$this->save($c,self::META_ANNOTATIONS,$o);}
 public function connections(Campaign $c):array{$o=[];foreach($this->decoded($c,self::META_CONNECTIONS) as $v){if(!is_array($v))continue;$id=sanitize_key((string)($v['id']??''));$from=$this->endpoint($v['from']??'');$to=$this->endpoint($v['to']??'');if($id!==''&&$from!==''&&$to!==''&&$from!==$to)$o[]=['id'=>$id,'from'=>$from,'to'=>$to];}return$o;}
 public function saveConnections(Campaign $c,array $a,array $allowed):void{$allow=array_fill_keys(array_map(fn($v)=>$this->endpoint($v),$allowed),true);$o=[];foreach($a as $v){if(!is_array($v))continue;$id=sanitize_key((string)($v['id']??''));$from=$this->endpoint($v['from']??'');$to=$this->endpoint($v['to']??'');if($id!==''&&$from!==''&&$to!==''&&$from!==$to&&isset($allow[$from],$allow[$to]))$o[]=['id'=>$id,'from'=>$from,'to'=>$to];}$this->save($c,self::META_CONNECTIONS,$o);}
 public function hiddenRecords(Campaign $c):array{return array_values(array_unique(array_filter(array_map(fn($v)=>$this->endpoint($v),$this->decoded($c,self::META_HIDDEN_RECORDS)))));}
 public function saveHiddenRecords(Campaign $c,array $keys,array $allowed):void{$allow=array_fill_keys(array_map(fn($v)=>$this->endpoint($v),$allowed),true);$o=[];foreach($keys as $k){$k=$this->endpoint($k);if(isset($allow[$k]))$o[]=$k;}$this->save($c,self::META_HIDDEN_RECORDS,array_values(array_unique($o)));}
 private function style(mixed $v):string{$v=sanitize_key((string)$v);return in_array($v,['parchment','yellow','warning'],true)?$v:'parchment';}
 private function endpoint(mixed $v):string{return preg_replace('/[^A-Za-z0-9_-]/','',(string)$v)??'';}
 private function pct(mixed $v):float{return max(0,min(100,(float)$v));}
 private function dimension(mixed $v,float $min,float $max):float{$v=(float)$v;return $v<=0?0:max($min,min($max,$v));}
 private function angle(mixed $v):float{return max(-4,min(4,(float)$v));}
 private function decoded(Campaign $c,string $key):array{$raw=get_post_meta($this->postId($c),$key,true);$d=is_string($raw)?json_decode($raw,true):$raw;return is_array($d)?$d:[];}
 private function save(Campaign $c,string $key,array $v):void{update_post_meta($this->postId($c),$key,wp_json_encode($v));}
 private function postId(Campaign $c):int{$id=$this->campaigns->postIdForOwner($c->id(),$c->ownerId());if($id===null)throw new RuntimeException('The Campaign Register record could not be found for this Conspiracy Board.');return$id;}
}