<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\EvidenceRecord;use RuntimeException;use WP_Post;
defined('ABSPATH') || exit;
final class EvidenceRepository
{
 public const POST_TYPE='gmrc_dm_evidence';private const META_ID='_gmrc_evidence_id';private const META_CAMPAIGN='_gmrc_evidence_campaign_id';private const META_RECORD_TYPE='_gmrc_evidence_record_type';private const META_KIND='_gmrc_evidence_kind';private const META_SUMMARY='_gmrc_evidence_summary';private const META_NOTES='_gmrc_evidence_notes';private const META_VISIBILITY='_gmrc_evidence_visibility';private const META_STATUS='_gmrc_evidence_status';private const META_THREADS='_gmrc_evidence_thread_ids';private const META_LOCATIONS='_gmrc_evidence_location_ids';private const META_PERSONAE='_gmrc_evidence_persona_ids';
 public function __construct(private CampaignRepository $campaigns){}
 /** @return EvidenceRecord[] */public function allForCampaign(Campaign $campaign):array{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>-1,'author'=>$campaign->ownerId(),'meta_key'=>self::META_CAMPAIGN,'meta_value'=>$campaign->id(),'orderby'=>'title','order'=>'ASC']);return array_map(fn(WP_Post $post):EvidenceRecord=>$this->map($post),$posts);}
 public function findForCampaign(string $id,Campaign $campaign):?EvidenceRecord{$post=$this->findPost($id,$campaign);return $post instanceof WP_Post?$this->map($post):null;}
 public function save(EvidenceRecord $record,Campaign $campaign):void{if($record->campaignId()!==$campaign->id()||$record->ownerId()!==$campaign->ownerId()){throw new RuntimeException('The Evidence Register record does not belong to this Campaign.');}$parent=$this->campaigns->postIdForOwner($campaign->id(),$campaign->ownerId());if($parent===null){throw new RuntimeException('The Campaign Register record could not be found.');}$existing=$this->findPost($record->id(),$campaign);$payload=['post_type'=>self::POST_TYPE,'post_status'=>'publish','post_title'=>$record->name(),'post_author'=>$campaign->ownerId(),'post_parent'=>$parent];if($existing instanceof WP_Post){$payload['ID']=$existing->ID;$postId=wp_update_post($payload,true);}else{$postId=wp_insert_post($payload,true);}if(is_wp_error($postId)||(int)$postId<1){throw new RuntimeException('The record could not be written to the Evidence Register.');}foreach([self::META_ID=>$record->id(),self::META_CAMPAIGN=>$campaign->id(),self::META_RECORD_TYPE=>$record->recordType(),self::META_KIND=>$record->evidenceKind(),self::META_SUMMARY=>$record->summary(),self::META_NOTES=>$record->notes(),self::META_VISIBILITY=>$record->visibility(),self::META_STATUS=>$record->status(),self::META_THREADS=>wp_json_encode($record->threadIds()),self::META_LOCATIONS=>wp_json_encode($record->locationIds()),self::META_PERSONAE=>wp_json_encode($record->personaIds())] as $key=>$value){update_post_meta((int)$postId,$key,$value);}}
 private function findPost(string $id,Campaign $campaign):?WP_Post{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>2,'author'=>$campaign->ownerId(),'meta_query'=>[['key'=>self::META_ID,'value'=>$id],['key'=>self::META_CAMPAIGN,'value'=>$campaign->id()]]]);if(count($posts)>1){throw new RuntimeException('Evidence Register contains duplicate records.');}$post=$posts[0]??null;return $post instanceof WP_Post?$post:null;}
 private function map(WP_Post $post):EvidenceRecord{return EvidenceRecord::restore((string)get_post_meta($post->ID,self::META_ID,true),(string)get_post_meta($post->ID,self::META_CAMPAIGN,true),(int)$post->post_author,(string)$post->post_title,(string)get_post_meta($post->ID,self::META_RECORD_TYPE,true),(string)get_post_meta($post->ID,self::META_KIND,true),(string)get_post_meta($post->ID,self::META_SUMMARY,true),(string)get_post_meta($post->ID,self::META_NOTES,true),(string)get_post_meta($post->ID,self::META_VISIBILITY,true),(string)get_post_meta($post->ID,self::META_STATUS,true),$this->ids($post->ID,self::META_THREADS),$this->ids($post->ID,self::META_LOCATIONS),$this->ids($post->ID,self::META_PERSONAE));}
 /** @return list<string> */private function ids(int $postId,string $key):array{$decoded=json_decode((string)get_post_meta($postId,$key,true),true);return is_array($decoded)?array_values(array_filter($decoded,'is_string')):[];}
}
