<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Location;use RuntimeException;use WP_Post;
defined('ABSPATH') || exit;
final class LocationRepository
{
 public const POST_TYPE='gmrc_dm_location'; private const META_ID='_gmrc_location_id';private const META_CAMPAIGN='_gmrc_location_campaign_id';private const META_TYPE='_gmrc_location_type';private const META_SUMMARY='_gmrc_location_summary';private const META_NOTES='_gmrc_location_notes';private const META_PARENT='_gmrc_location_parent_id';private const META_VISIBILITY='_gmrc_location_visibility';private const META_STATUS='_gmrc_location_status';private const META_TABLETOP_SCENE='_gmrc_location_tabletop_scene_id';
 public function __construct(private CampaignRepository $campaigns){}
 /** @return Location[] */ public function allForCampaign(Campaign $campaign):array{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>-1,'author'=>$campaign->ownerId(),'meta_key'=>self::META_CAMPAIGN,'meta_value'=>$campaign->id(),'orderby'=>'title','order'=>'ASC']);return array_map(fn(WP_Post $post):Location=>$this->map($post),$posts);}
 public function findForCampaign(string $id,Campaign $campaign):?Location{$post=$this->findPost($id,$campaign);return $post instanceof WP_Post?$this->map($post):null;}
 public function save(Location $location,Campaign $campaign):void{if($location->campaignId()!==$campaign->id()||$location->ownerId()!==$campaign->ownerId()){throw new RuntimeException('The Gazetteer location does not belong to this Campaign.');}$parent=$this->campaigns->postIdForOwner($campaign->id(),$campaign->ownerId());if($parent===null){throw new RuntimeException('The Campaign Register record could not be found.');}$existing=$this->findPost($location->id(),$campaign);$payload=['post_type'=>self::POST_TYPE,'post_status'=>'publish','post_title'=>$location->name(),'post_author'=>$campaign->ownerId(),'post_parent'=>$parent];if($existing instanceof WP_Post){$payload['ID']=$existing->ID;$postId=wp_update_post($payload,true);}else{$postId=wp_insert_post($payload,true);}if(is_wp_error($postId)||(int)$postId<1){throw new RuntimeException('The location could not be written to the Keeper’s Gazetteer.');}foreach([self::META_ID=>$location->id(),self::META_CAMPAIGN=>$campaign->id(),self::META_TYPE=>$location->type(),self::META_SUMMARY=>$location->summary(),self::META_NOTES=>$location->notes(),self::META_PARENT=>$location->parentId(),self::META_VISIBILITY=>$location->visibility(),self::META_STATUS=>$location->status(),self::META_TABLETOP_SCENE=>$location->tabletopSceneId()] as $key=>$value){update_post_meta((int)$postId,$key,$value);}}
 private function findPost(string $id,Campaign $campaign):?WP_Post{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>2,'author'=>$campaign->ownerId(),'meta_query'=>[['key'=>self::META_ID,'value'=>$id],['key'=>self::META_CAMPAIGN,'value'=>$campaign->id()]]]);if(count($posts)>1){throw new RuntimeException('The Keeper’s Gazetteer contains duplicate location records.');}$post=$posts[0]??null;return $post instanceof WP_Post?$post:null;}
 private function map(WP_Post $post):Location{return Location::restore((string)get_post_meta($post->ID,self::META_ID,true),(string)get_post_meta($post->ID,self::META_CAMPAIGN,true),(int)$post->post_author,(string)$post->post_title,(string)get_post_meta($post->ID,self::META_TYPE,true),(string)get_post_meta($post->ID,self::META_SUMMARY,true),(string)get_post_meta($post->ID,self::META_NOTES,true),(string)get_post_meta($post->ID,self::META_PARENT,true),(string)get_post_meta($post->ID,self::META_VISIBILITY,true),(string)get_post_meta($post->ID,self::META_STATUS,true),(string)get_post_meta($post->ID,self::META_TABLETOP_SCENE,true));}
}
