<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Persona;use RuntimeException;use WP_Post;
defined('ABSPATH') || exit;
final class PersonaRepository
{
 public const POST_TYPE='gmrc_dm_persona';private const META_ID='_gmrc_persona_id';private const META_CAMPAIGN='_gmrc_persona_campaign_id';private const META_KIND='_gmrc_persona_kind';private const META_ROLE='_gmrc_persona_role';private const META_SUMMARY='_gmrc_persona_summary';private const META_NOTES='_gmrc_persona_notes';private const META_VISIBILITY='_gmrc_persona_visibility';private const META_STATUS='_gmrc_persona_status';private const META_FACTION='_gmrc_persona_faction_id';
 public function __construct(private CampaignRepository $campaigns){}
 /** @return Persona[] */public function allForCampaign(Campaign $campaign):array{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>-1,'author'=>$campaign->ownerId(),'meta_key'=>self::META_CAMPAIGN,'meta_value'=>$campaign->id(),'orderby'=>'title','order'=>'ASC']);return array_map(fn(WP_Post $post):Persona=>$this->map($post),$posts);}
 public function findForCampaign(string $id,Campaign $campaign):?Persona{$post=$this->findPost($id,$campaign);return $post instanceof WP_Post?$this->map($post):null;}
 public function save(Persona $persona,Campaign $campaign):void{if($persona->campaignId()!==$campaign->id()||$persona->ownerId()!==$campaign->ownerId()){throw new RuntimeException('The Dramatis Personae record does not belong to this Campaign.');}$parent=$this->campaigns->postIdForOwner($campaign->id(),$campaign->ownerId());if($parent===null){throw new RuntimeException('The Campaign Register record could not be found.');}$existing=$this->findPost($persona->id(),$campaign);$payload=['post_type'=>self::POST_TYPE,'post_status'=>'publish','post_title'=>$persona->name(),'post_author'=>$campaign->ownerId(),'post_parent'=>$parent];if($existing instanceof WP_Post){$payload['ID']=$existing->ID;$postId=wp_update_post($payload,true);}else{$postId=wp_insert_post($payload,true);}if(is_wp_error($postId)||(int)$postId<1){throw new RuntimeException('The record could not be written to Dramatis Personae.');}foreach([self::META_ID=>$persona->id(),self::META_CAMPAIGN=>$campaign->id(),self::META_KIND=>$persona->kind(),self::META_ROLE=>$persona->role(),self::META_SUMMARY=>$persona->summary(),self::META_NOTES=>$persona->notes(),self::META_VISIBILITY=>$persona->visibility(),self::META_STATUS=>$persona->status(),self::META_FACTION=>$persona->factionId()] as $key=>$value){update_post_meta((int)$postId,$key,$value);}}
 private function findPost(string $id,Campaign $campaign):?WP_Post{$posts=get_posts(['post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>2,'author'=>$campaign->ownerId(),'meta_query'=>[['key'=>self::META_ID,'value'=>$id],['key'=>self::META_CAMPAIGN,'value'=>$campaign->id()]]]);if(count($posts)>1){throw new RuntimeException('Dramatis Personae contains duplicate records.');}$post=$posts[0]??null;return $post instanceof WP_Post?$post:null;}
 private function map(WP_Post $post):Persona{return Persona::restore((string)get_post_meta($post->ID,self::META_ID,true),(string)get_post_meta($post->ID,self::META_CAMPAIGN,true),(int)$post->post_author,(string)$post->post_title,(string)get_post_meta($post->ID,self::META_KIND,true),(string)get_post_meta($post->ID,self::META_ROLE,true),(string)get_post_meta($post->ID,self::META_SUMMARY,true),(string)get_post_meta($post->ID,self::META_NOTES,true),(string)get_post_meta($post->ID,self::META_VISIBILITY,true),(string)get_post_meta($post->ID,self::META_STATUS,true),(string)get_post_meta($post->ID,self::META_FACTION,true));}
}
