<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Models;
use GreatMarketrealmCompanion\Core\Support\Ulid;use InvalidArgumentException;
defined('ABSPATH') || exit;
final class EvidenceRecord
{
 public const RECORD_TYPES=['evidence','thread'];public const EVIDENCE_KINDS=['clue','document','rumour','object','testimony','discovery','secret','other'];public const VISIBILITIES=['keeper','players'];public const STATUSES=['active','archived'];
 /** @param list<string> $threadIds @param list<string> $locationIds @param list<string> $personaIds */
 private function __construct(private string $id,private string $campaignId,private int $ownerId,private string $name,private string $recordType,private string $evidenceKind,private string $summary,private string $notes,private string $visibility,private string $status,private array $threadIds=[],private array $locationIds=[],private array $personaIds=[]){if(!Ulid::isValid($id)||!Ulid::isValid($campaignId)||$ownerId<1){throw new InvalidArgumentException('Invalid Evidence Register identity.');}if(!in_array($recordType,self::RECORD_TYPES,true)||!in_array($visibility,self::VISIBILITIES,true)||!in_array($status,self::STATUSES,true)){throw new InvalidArgumentException('Invalid Evidence Register classification.');}if($recordType==='evidence'&&!in_array($evidenceKind,self::EVIDENCE_KINDS,true)){throw new InvalidArgumentException('Invalid evidence kind.');}if($recordType==='thread'){$this->evidenceKind='';}$this->threadIds=$this->ids($threadIds);$this->locationIds=$this->ids($locationIds);$this->personaIds=$this->ids($personaIds);}
 /** @param list<string> $threadIds @param list<string> $locationIds @param list<string> $personaIds */public static function create(string $campaignId,int $ownerId,string $name,string $recordType,string $evidenceKind,string $summary,string $notes,string $visibility,array $threadIds=[],array $locationIds=[],array $personaIds=[]):self{return new self(Ulid::generate(),$campaignId,$ownerId,$name,$recordType,$evidenceKind,$summary,$notes,$visibility,'active',$threadIds,$locationIds,$personaIds);}
 /** @param list<string> $threadIds @param list<string> $locationIds @param list<string> $personaIds */public static function restore(string $id,string $campaignId,int $ownerId,string $name,string $recordType,string $evidenceKind,string $summary,string $notes,string $visibility,string $status,array $threadIds=[],array $locationIds=[],array $personaIds=[]):self{return new self($id,$campaignId,$ownerId,$name,$recordType,$evidenceKind,$summary,$notes,$visibility,$status,$threadIds,$locationIds,$personaIds);}
 /** @param list<string> $threadIds @param list<string> $locationIds @param list<string> $personaIds */public function update(string $name,string $recordType,string $evidenceKind,string $summary,string $notes,string $visibility,array $threadIds=[],array $locationIds=[],array $personaIds=[]):void{if(!in_array($recordType,self::RECORD_TYPES,true)||!in_array($visibility,self::VISIBILITIES,true)){throw new InvalidArgumentException('Invalid Evidence Register classification.');}if($recordType==='thread'){$evidenceKind='';$threadIds=[];}elseif(!in_array($evidenceKind,self::EVIDENCE_KINDS,true)){throw new InvalidArgumentException('Invalid evidence kind.');}$this->name=$name;$this->recordType=$recordType;$this->evidenceKind=$evidenceKind;$this->summary=$summary;$this->notes=$notes;$this->visibility=$visibility;$this->threadIds=$this->ids($threadIds);$this->locationIds=$this->ids($locationIds);$this->personaIds=$this->ids($personaIds);}
 public function archive():void{$this->status='archived';}
 public function id():string{return $this->id;}public function campaignId():string{return $this->campaignId;}public function ownerId():int{return $this->ownerId;}public function name():string{return $this->name;}public function recordType():string{return $this->recordType;}public function evidenceKind():string{return $this->evidenceKind;}public function summary():string{return $this->summary;}public function notes():string{return $this->notes;}public function visibility():string{return $this->visibility;}public function status():string{return $this->status;}public function threadIds():array{return $this->threadIds;}public function locationIds():array{return $this->locationIds;}public function personaIds():array{return $this->personaIds;}public function isThread():bool{return $this->recordType==='thread';}public function isArchived():bool{return $this->status==='archived';}public function isKeeperOnly():bool{return $this->visibility==='keeper';}public function typeLabel():string{return $this->isThread()?'Thread':ucfirst($this->evidenceKind);}
 /** @param list<string> $values @return list<string> */private function ids(array $values):array{$clean=[];foreach($values as $value){$value=trim((string)$value);if($value===''||!Ulid::isValid($value)){throw new InvalidArgumentException('Invalid Evidence Register relationship identity.');}$clean[$value]=$value;}return array_values($clean);}
}
