<?php defined('ABSPATH') || exit; $base=home_url('/companion/'); $route='dungeon-master/campaigns/'.$campaign->id().'/encounters/'.$encounter->id().'/initiative'; $combatants=$table->combatants(); $archived=$campaign->isArchived(); ?>
<section class="gmrc-initiative-table" data-initiative-table>
<header class="gmrc-initiative-table__hero"><div><p class="gmrc-dm-desk__eyebrow">Live Encounter · Round <?php echo esc_html((string)$table->round()); ?></p><h1>The Initiative Table</h1><p><strong><?php echo esc_html($encounter->title()); ?></strong> · Track the order of battle without losing the Encounter Board beneath it.</p></div><a class="gmrc-initiative-button gmrc-initiative-button--ghost" href="<?php echo esc_url(add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaign->id().'/encounters/'.$encounter->id(),$base)); ?>">← Encounter</a></header>
<?php if(!empty($flash['success'])): ?><p class="gmrc-initiative-flash" role="status"><?php echo esc_html($flash['success']); ?></p><?php endif; ?>
<?php if($archived): ?><p class="gmrc-initiative-notice">This Campaign is archived. Its final Initiative Table is preserved as read-only history.</p><?php endif; ?>
<?php if($combatants===[]): ?><article class="gmrc-initiative-empty"><h2>The table is waiting for combatants</h2><p>Add participating Characters or adversaries to the Encounter Board, then return here.</p></article><?php else: ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-initiative-form">
<input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($route); ?>"><input type="hidden" name="_method" value="PUT"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_initiative_'.$campaign->id().'_'.$encounter->id())); ?>"><input type="hidden" name="round" value="<?php echo esc_attr((string)$table->round()); ?>"><input type="hidden" name="turn_index" value="<?php echo esc_attr((string)$table->turnIndex()); ?>">
<div class="gmrc-initiative-toolbar"><div><span>Round</span><strong><?php echo esc_html((string)$table->round()); ?></strong></div><div><span>Active turn</span><strong><?php echo esc_html((string)($table->turnIndex()+1).' / '.count($combatants)); ?></strong></div><?php if(!$archived): ?><button class="gmrc-initiative-button" type="submit" name="initiative_action" value="advance">Advance Turn →</button><button class="gmrc-initiative-button gmrc-initiative-button--ghost" type="submit" name="initiative_action" value="sort">Sort Initiative</button><?php endif; ?></div>
<ol class="gmrc-initiative-order">
<?php foreach($combatants as $index=>$combatant): $active=$index===$table->turnIndex(); ?>
<li class="gmrc-initiative-combatant<?php echo $active?' is-active':''; ?><?php echo !empty($combatant['defeated'])?' is-defeated':''; ?>" <?php echo $active?'aria-current="step"':''; ?>>
<input type="hidden" name="combatants[<?php echo esc_attr((string)$index); ?>][id]" value="<?php echo esc_attr((string)$combatant['id']); ?>">
<div class="gmrc-initiative-combatant__identity"><span><?php echo esc_html($combatant['type']==='character'?'Adventurer':'Adversary'); ?></span><strong><?php echo esc_html((string)$combatant['name']); ?></strong><?php if($active): ?><em>Taking turn</em><?php endif; ?></div>
<label>Initiative <span class="gmrc-initiative-roll"><input type="number" min="-20" max="99" name="combatants[<?php echo esc_attr((string)$index); ?>][initiative]" value="<?php echo esc_attr((string)$combatant['initiative']); ?>" <?php disabled($archived); ?>><?php if(!$archived): ?><button type="button" data-roll-initiative data-modifier="<?php echo esc_attr((string)($combatant['modifier']??0)); ?>" aria-label="Roll initiative for <?php echo esc_attr((string)$combatant['name']); ?>">🎲</button><?php endif; ?></span></label>
<label>HP <span class="gmrc-initiative-hp"><input type="number" min="0" max="99999" name="combatants[<?php echo esc_attr((string)$index); ?>][current_hp]" value="<?php echo esc_attr((string)$combatant['current_hp']); ?>" <?php disabled($archived); ?>><span>/</span><input type="number" min="0" max="99999" name="combatants[<?php echo esc_attr((string)$index); ?>][max_hp]" value="<?php echo esc_attr((string)$combatant['max_hp']); ?>" <?php disabled($archived); ?> <?php echo $combatant['type']==='character'?'readonly aria-readonly="true"':''; ?>></span></label>
<label>Conditions <input type="text" maxlength="180" name="combatants[<?php echo esc_attr((string)$index); ?>][conditions]" value="<?php echo esc_attr((string)$combatant['conditions']); ?>" placeholder="Poisoned, prone…" <?php disabled($archived); ?>></label>
<?php if(!$archived): ?><label class="gmrc-initiative-defeated"><input type="checkbox" name="combatants[<?php echo esc_attr((string)$index); ?>][defeated]" value="1" <?php checked(!empty($combatant['defeated'])); ?>> Down</label><?php endif; ?>
</li><?php endforeach; ?>
</ol>
<?php if(!$archived): ?><div class="gmrc-initiative-actions"><button class="gmrc-initiative-button" type="submit" name="initiative_action" value="save">Save Table</button><button class="gmrc-initiative-button gmrc-initiative-button--ghost" type="submit" name="initiative_action" value="reset">Reset from Encounter</button><button class="gmrc-initiative-button gmrc-initiative-button--danger" type="submit" name="initiative_action" value="complete">Complete Encounter</button></div><?php endif; ?>
<p class="gmrc-initiative-live" aria-live="polite" data-initiative-live></p></form><?php endif; ?></section>
