<?php
use GreatMarketrealmCompanion\Core\Routing\Router;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\DungeonMasterController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\CampaignController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\PlayerRosterController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\SessionController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\EncounterController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\InitiativeController;
use GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers\MonsterController;
defined('ABSPATH') || exit;
return static function (Router $router): void {
 $router->get('/dungeon-master',[DungeonMasterController::class,'index']);

 $router->get('/dungeon-master/monsters',[MonsterController::class,'index']);
 $router->get('/dungeon-master/monsters/create',[MonsterController::class,'create']);
 $router->post('/dungeon-master/monsters',[MonsterController::class,'store']);
 $router->get('/dungeon-master/monsters/{monsterId}/edit',[MonsterController::class,'edit']);
 $router->get('/dungeon-master/monsters/{monsterId}',[MonsterController::class,'show']);
 $router->put('/dungeon-master/monsters/{monsterId}',[MonsterController::class,'update']);
 $router->post('/dungeon-master/monsters/{monsterId}/archive',[MonsterController::class,'archive']);
 $router->get('/dungeon-master/campaigns',[CampaignController::class,'index']);
 $router->get('/dungeon-master/campaigns/create',[CampaignController::class,'create']);
 $router->post('/dungeon-master/campaigns',[CampaignController::class,'store']);
 $router->get('/dungeon-master/campaigns/{id}/edit',[CampaignController::class,'edit']);
 $router->get('/dungeon-master/campaigns/{id}',[CampaignController::class,'show']);
 $router->put('/dungeon-master/campaigns/{id}',[CampaignController::class,'update']);
 $router->post('/dungeon-master/campaigns/{id}/archive',[CampaignController::class,'archive']);
 $router->get('/dungeon-master/campaigns/{id}/players',[PlayerRosterController::class,'index']);
 $router->post('/dungeon-master/campaigns/{id}/players',[PlayerRosterController::class,'store']);
 $router->delete('/dungeon-master/campaigns/{id}/players/{playerId}',[PlayerRosterController::class,'destroy']);
 $router->post('/dungeon-master/campaigns/{id}/players/{playerId}/characters/{characterId}',[PlayerRosterController::class,'attachCharacter']);
 $router->delete('/dungeon-master/campaigns/{id}/players/{playerId}/characters/{characterId}',[PlayerRosterController::class,'detachCharacter']);
 $router->get('/dungeon-master/campaigns/{id}/sessions',[SessionController::class,'index']);
 $router->get('/dungeon-master/campaigns/{id}/sessions/create',[SessionController::class,'create']);
 $router->post('/dungeon-master/campaigns/{id}/sessions',[SessionController::class,'store']);
 $router->get('/dungeon-master/campaigns/{id}/sessions/{sessionId}/edit',[SessionController::class,'edit']);
 $router->get('/dungeon-master/campaigns/{id}/sessions/{sessionId}',[SessionController::class,'show']);
 $router->put('/dungeon-master/campaigns/{id}/sessions/{sessionId}',[SessionController::class,'update']);
 $router->get('/dungeon-master/campaigns/{id}/encounters',[EncounterController::class,'index']);
 $router->get('/dungeon-master/campaigns/{id}/encounters/create',[EncounterController::class,'create']);
 $router->post('/dungeon-master/campaigns/{id}/encounters',[EncounterController::class,'store']);
 $router->get('/dungeon-master/campaigns/{id}/encounters/{encounterId}/edit',[EncounterController::class,'edit']);
 $router->get('/dungeon-master/campaigns/{id}/encounters/{encounterId}',[EncounterController::class,'show']);
 $router->put('/dungeon-master/campaigns/{id}/encounters/{encounterId}',[EncounterController::class,'update']);
 $router->get('/dungeon-master/campaigns/{id}/encounters/{encounterId}/initiative',[InitiativeController::class,'index']);
 $router->put('/dungeon-master/campaigns/{id}/encounters/{encounterId}/initiative',[InitiativeController::class,'update']);
};
