<?php

declare(strict_types=1);
use GreatMarketrealmCompanion\Modules\Administration\Workshop\BackgroundWorkshop;
use GreatMarketrealmCompanion\Modules\Characters\Models\ValueObjects\SkillProficiencies;
use GreatMarketrealmCompanion\Modules\Characters\Models\ValueObjects\ToolProficiency;

defined('ABSPATH') || exit;
$stewardBackgrounds=is_array($stewardBackgrounds??null)?$stewardBackgrounds:[];
$selectedBackground=is_array($selectedBackground??null)?$selectedBackground:null;
$isNew=$selectedBackground===null;
$status=$isNew?BackgroundWorkshop::STATUS_DRAFT:(string)($selectedBackground['status']??BackgroundWorkshop::STATUS_DRAFT);
$value=static fn(string $key,string $fallback=''):string=>$isNew?$fallback:(string)($selectedBackground[$key]??$fallback);
$recordsUrl=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'background-workshop'],admin_url('admin.php'));
$checkedSkills=is_array($selectedBackground['skills']??null)?$selectedBackground['skills']:[];
$checkedTools=is_array($selectedBackground['tools']??null)?$selectedBackground['tools']:[];
?>
<div class="wrap gmrc-admin gmrc-stewards-office gmrc-canonical-steward gmrc-background-workshop">
<header class="gmrc-stewards-office__hero"><p class="gmrc-stewards-office__eyebrow">Steward-authored content · Background Workshop</p><h1>The Steward's Background Workshop</h1><p>Create new Marketrealm histories without editing PHP. Drafts remain private, mechanically complete Published backgrounds become available to future Characters and the Guild Library, and Archived records remain preserved but unavailable to new inscriptions.</p></header>
<?php if(isset($_GET['gmrc_background_workshop_saved'])):?><div class="notice notice-success is-dismissible"><p>The Steward background has been sealed.</p></div><?php endif;?>
<?php if(isset($_GET['gmrc_background_workshop_error'])):?><div class="notice notice-error"><p><?php echo esc_html(rawurldecode((string)$_GET['gmrc_background_workshop_error']));?></p></div><?php endif;?>
<div class="gmrc-canonical-steward__layout">
<aside class="gmrc-canonical-steward__register"><div class="gmrc-canonical-steward__register-head"><h2>Steward Backgrounds</h2><a class="button button-primary" href="<?php echo esc_url($recordsUrl);?>">Add Background</a></div><?php if($stewardBackgrounds===[]):?><p>No custom backgrounds have been recorded yet.</p><?php endif;?><div class="gmrc-canonical-steward__list"><?php foreach($stewardBackgrounds as $key=>$data):$url=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'background-workshop','background'=>$key],admin_url('admin.php'));?><a href="<?php echo esc_url($url);?>"<?php echo !$isNew && ($selectedBackground['key']??'')===$key?' aria-current="page"':'';?>><span class="gmrc-canonical-steward__thumb" aria-hidden="true">✦</span><span><strong><?php echo esc_html((string)($data['name']??'Untitled Background'));?></strong><small><?php echo esc_html(ucfirst((string)($data['status']??'draft')));?></small></span></a><?php endforeach;?></div><p><a href="<?php echo esc_url(add_query_arg(['page'=>'gmrc-stewards-office','section'=>'canonical-backgrounds'],admin_url('admin.php')));?>">Review protected canonical Background Register →</a></p></aside>
<main class="gmrc-canonical-steward__editor"><form class="gmrc-canonical-steward__form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="gmrc_save_steward_background"><input type="hidden" name="background_key" value="<?php echo esc_attr($isNew?'':(string)$selectedBackground['key']);?>"><?php wp_nonce_field('gmrc_save_steward_background_'.($isNew?'new':(string)$selectedBackground['key']),'gmrc_steward_background_nonce');?><header><div><p class="gmrc-stewards-office__eyebrow"><?php echo $isNew?'New shared background':'Editing Steward background';?></p><h2><?php echo esc_html($isNew?'Untitled Background':(string)$selectedBackground['name']);?></h2></div><span class="gmrc-stewards-office__status"><?php echo esc_html(ucfirst($status));?></span></header>
<div class="gmrc-canonical-steward__fields"><label><strong>Name</strong><input name="name" type="text" required value="<?php echo esc_attr($value('name'));?>"></label><label><strong>Publication</strong><select name="status"><option value="draft"<?php selected($status,'draft');?>>Draft</option><option value="published"<?php selected($status,'published');?>>Published</option><option value="archived"<?php selected($status,'archived');?>>Archived</option></select></label><label><strong>Feature name</strong><input name="feature_name" type="text" value="<?php echo esc_attr($value('feature_name'));?>" placeholder="Market Ear"></label><label><strong>Languages / language notes</strong><input name="languages" type="text" value="<?php echo esc_attr($value('languages'));?>" placeholder="None, or describe the grant"></label></div>
<label><strong>Feature rules</strong><textarea name="feature_detail" rows="7" placeholder="Describe the complete Background feature."><?php echo esc_textarea($value('feature_detail'));?></textarea></label>
<fieldset class="gmrc-spell-workshop__access"><legend>Skill proficiencies — choose exactly two to publish</legend><?php foreach(SkillProficiencies::supportedSkills() as $id):?><label><input type="checkbox" name="skills[]" value="<?php echo esc_attr($id);?>"<?php checked(in_array($id,$checkedSkills,true));?>> <?php echo esc_html(ucwords(str_replace('-', ' ', $id)));?></label><?php endforeach;?></fieldset>
<fieldset class="gmrc-spell-workshop__access"><legend>Tool proficiency — choose exactly one to publish</legend><?php foreach(ToolProficiency::all() as $tool):$id=$tool->value();?><label><input type="checkbox" name="tools[]" value="<?php echo esc_attr($id);?>"<?php checked(in_array($id,$checkedTools,true));?>> <?php echo esc_html($tool->label());?></label><?php endforeach;?></fieldset>
<label><strong>Starting equipment / possessions</strong><textarea name="starting_equipment" rows="4" placeholder="Record the Background's suggested possessions. This is reference text until Background equipment grants receive their own certified mechanics bridge."><?php echo esc_textarea($value('starting_equipment'));?></textarea></label>
<label><strong>Steward notes</strong><textarea name="steward_notes" rows="5" placeholder="Balance notes, design intent, table rulings…"><?php echo esc_textarea($value('steward_notes'));?></textarea></label>
<aside class="gmrc-canonical-steward__source"><strong>Publication safeguard:</strong> Published backgrounds require a named feature, complete feature rules, exactly two recognised skills and one recognised tool. Their stable <code>steward-background-*</code> identity cannot overwrite a canonical Handbook background. Starting-equipment and language notes are reference-only in this phase and never invent Character mechanics.</aside><div class="gmrc-canonical-steward__actions"><button class="button button-primary button-large" type="submit"><?php echo $isNew?'Create Steward Background':'Seal Steward Background';?></button><a class="button" href="<?php echo esc_url($recordsUrl);?>">New background</a></div></form></main>
</div></div>
