<?php
use GreatMarketrealmCompanion\Modules\Administration\Workshop\CallingWorkshop;
defined('ABSPATH') || exit;
$isNew = ! is_array($selectedCalling ?? null);
$calling = $isNew ? [] : $selectedCalling;
$status = $isNew ? CallingWorkshop::STATUS_DRAFT : (string) ($calling['status'] ?? CallingWorkshop::STATUS_DRAFT);
$value = static fn (string $key): string => (string) ($calling[$key] ?? '');
$checkedSaves = array_values((array) ($calling['saving_throws'] ?? []));
$pathLines=[]; foreach ((array)($calling['paths']??[]) as $path) if(is_array($path)) $pathLines[]=implode(' | ',[(string)($path['name']??''),(string)($path['selection_level']??''),(string)($path['description']??''),(string)($path['identity']??''),(string)($path['playstyle']??'')]);
$baseUrl=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'calling-workshop'],admin_url('admin.php'));
?>
<div class="wrap gmrc-admin gmrc-canonical-steward gmrc-calling-workshop">
<header class="gmrc-canonical-steward__hero"><div><p class="gmrc-stewards-office__eyebrow">Steward-authored rules · Custom Calling Registry</p><h1>Class &amp; Calling Path Workshop</h1><p>Create mechanically bounded Callings and their specialist Paths without altering protected Players Handbook canon.</p></div><a class="button" href="<?php echo esc_url(add_query_arg(['page'=>'gmrc-stewards-office'],admin_url('admin.php')));?>">Back to Steward's Office</a></header>
<?php if(isset($_GET['gmrc_calling_workshop_saved'])):?><div class="notice notice-success"><p>Steward Calling saved.</p></div><?php endif;?>
<?php if(isset($_GET['gmrc_calling_workshop_error'])):?><div class="notice notice-error"><p><?php echo esc_html(rawurldecode((string)$_GET['gmrc_calling_workshop_error']));?></p></div><?php endif;?>
<div class="gmrc-canonical-steward__workspace">
<aside class="gmrc-canonical-steward__register"><div class="gmrc-canonical-steward__register-head"><h2>Steward Callings</h2><a class="button button-primary" href="<?php echo esc_url($baseUrl);?>">Add Calling</a></div><?php if($stewardCallings===[]):?><p>No custom Callings have been recorded yet.</p><?php endif;?><div class="gmrc-canonical-steward__list"><?php foreach($stewardCallings as $key=>$data):$url=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'calling-workshop','calling'=>$key],admin_url('admin.php'));?><a href="<?php echo esc_url($url);?>"<?php echo !$isNew && ($calling['key']??'')===$key?' aria-current="page"':'';?>><span class="gmrc-canonical-steward__thumb" aria-hidden="true">⚔</span><span><strong><?php echo esc_html((string)($data['name']??'Untitled Calling'));?></strong><small><?php echo esc_html(ucfirst((string)($data['status']??'draft')));?></small></span></a><?php endforeach;?></div><p><a href="<?php echo esc_url(add_query_arg(['page'=>'gmrc-stewards-office','section'=>'canonical-callings'],admin_url('admin.php')));?>">Review protected canonical Calling Register →</a></p></aside>
<main class="gmrc-canonical-steward__editor"><form class="gmrc-canonical-steward__form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="gmrc_save_steward_calling"><input type="hidden" name="calling_key" value="<?php echo esc_attr($isNew?'':(string)$calling['key']);?>"><?php wp_nonce_field('gmrc_save_steward_calling_'.($isNew?'new':(string)$calling['key']),'gmrc_steward_calling_nonce');?><header><div><p class="gmrc-stewards-office__eyebrow"><?php echo $isNew?'New playable Calling':'Editing Steward Calling';?></p><h2><?php echo esc_html($isNew?'Untitled Calling':(string)$calling['name']);?></h2></div><span class="gmrc-stewards-office__status"><?php echo esc_html(ucfirst($status));?></span></header>
<div class="gmrc-canonical-steward__fields"><label><strong>Name</strong><input name="name" required value="<?php echo esc_attr($value('name'));?>"></label><label><strong>Status</strong><select name="status"><?php foreach(['draft'=>'Draft','published'=>'Published','archived'=>'Archived'] as $k=>$label):?><option value="<?php echo esc_attr($k);?>"<?php selected($status,$k);?>><?php echo esc_html($label);?></option><?php endforeach;?></select></label><label><strong>Hit die</strong><select name="hit_die"><option value="0">Unset</option><?php foreach([6,8,10,12] as $die):?><option value="<?php echo $die;?>"<?php selected((int)($calling['hit_die']??0),$die);?>>d<?php echo $die;?></option><?php endforeach;?></select></label><label><strong>Path choice level</strong><input type="number" min="1" max="20" name="path_level" value="<?php echo esc_attr((string)($calling['path_level']??3));?>"></label><label><strong>Calling Path label</strong><input name="path_label" value="<?php echo esc_attr($value('path_label')?:'Calling Path');?>" placeholder="Sacred Recipe, College, Circle…"></label></div>
<fieldset class="gmrc-spell-workshop__access"><legend>Saving throw proficiencies — choose exactly two to publish</legend><?php foreach(['strength','dexterity','constitution','intelligence','wisdom','charisma'] as $ability):?><label><input type="checkbox" name="saving_throws[]" value="<?php echo esc_attr($ability);?>"<?php checked(in_array($ability,$checkedSaves,true));?>> <?php echo esc_html(ucfirst($ability));?></label><?php endforeach;?></fieldset>
<label><strong>Calling description</strong><textarea name="description" rows="6"><?php echo esc_textarea($value('description'));?></textarea></label>
<section class="gmrc-spell-workshop__mechanics"><h3>Calling Paths</h3><p>One Path per line: <code>Name | selection level | description | identity | playstyle</code>. Published Paths become selectable only with their Published parent Calling.</p><textarea name="paths" rows="10" class="large-text code"><?php echo esc_textarea(implode("\n",$pathLines));?></textarea><p class="description">This Workshop certifies class identity, HP/saves and Path selection. Bespoke resources, spellcasting progressions and executable feature engines remain code-certified mechanics rather than being guessed from free text.</p></section>
<label><strong>Private Steward notes</strong><textarea name="steward_notes" rows="4"><?php echo esc_textarea($value('steward_notes'));?></textarea></label><?php submit_button($isNew?'Create Calling':'Save Calling');?></form></main>
</div></div>

<?php $deleteType = 'calling'; $deleteKey = $isNew ? '' : (string) ($calling['key'] ?? ''); $deleteLabel = $isNew ? 'this Calling' : (string) ($calling['name'] ?? 'this Calling'); require GMRC_PATH . 'app/Modules/Administration/Views/_steward-delete.php'; ?>
