<?php

declare(strict_types=1);
use GreatMarketrealmCompanion\Modules\Administration\Workshop\SpellWorkshop;

defined('ABSPATH') || exit;
$stewardSpells=is_array($stewardSpells??null)?$stewardSpells:[];
$selectedSpell=is_array($selectedSpell??null)?$selectedSpell:null;
$isNew=$selectedSpell===null;
$status=$isNew?SpellWorkshop::STATUS_DRAFT:(string)($selectedSpell['status']??SpellWorkshop::STATUS_DRAFT);
$value=static fn(string $key,string $fallback=''):string=>$isNew?$fallback:(string)($selectedSpell[$key]??$fallback);
$recordsUrl=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'spell-workshop'],admin_url('admin.php'));
$checkedAccess=is_array($selectedSpell['access_labels']??null)?$selectedSpell['access_labels']:[];
?>
<div class="wrap gmrc-admin gmrc-stewards-office gmrc-canonical-steward gmrc-spell-workshop">
<header class="gmrc-stewards-office__hero"><p class="gmrc-stewards-office__eyebrow">Steward-authored content · Spell Workshop</p><h1>The Steward's Spell Workshop</h1><p>Create new Marketrealm magic without editing PHP. Drafts remain private, mechanically complete Published spells join Sage’s Spellbook and eligible Character spell catalogues, and Archived records remain preserved but unavailable to new adventurers.</p></header>
<?php if(isset($_GET['gmrc_spell_workshop_saved'])):?><div class="notice notice-success is-dismissible"><p>The Steward spell has been sealed.</p></div><?php endif;?>
<?php if(isset($_GET['gmrc_spell_workshop_error'])):?><div class="notice notice-error"><p><?php echo esc_html(rawurldecode((string)$_GET['gmrc_spell_workshop_error']));?></p></div><?php endif;?>
<div class="gmrc-canonical-steward__layout">
<aside class="gmrc-canonical-steward__register"><div class="gmrc-canonical-steward__register-head"><h2>Steward Spells</h2><a class="button button-primary" href="<?php echo esc_url($recordsUrl);?>">Add Spell</a></div><?php if($stewardSpells===[]):?><p>No custom spells have been written yet.</p><?php endif;?><div class="gmrc-canonical-steward__list"><?php foreach($stewardSpells as $key=>$data):$url=add_query_arg(['page'=>'gmrc-stewards-office','section'=>'spell-workshop','spell'=>$key],admin_url('admin.php'));?><a href="<?php echo esc_url($url);?>"<?php echo !$isNew && ($selectedSpell['key']??'')===$key?' aria-current="page"':'';?>><span class="gmrc-canonical-steward__thumb" aria-hidden="true">✦</span><span><strong><?php echo esc_html((string)($data['name']??'Untitled Spell'));?></strong><small><?php echo esc_html(ucfirst((string)($data['status']??'draft')).' · '.(($data['level']??null)===0?'Cantrip':(($data['level']??null)!==null?'Level '.$data['level']:'Level unset')));?></small></span></a><?php endforeach;?></div><p><a href="<?php echo esc_url(add_query_arg(['page'=>'gmrc-stewards-office','section'=>'canonical-spells'],admin_url('admin.php')));?>">Review protected canonical Spell Register →</a></p></aside>
<main class="gmrc-canonical-steward__editor"><form class="gmrc-canonical-steward__form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="gmrc_save_steward_spell"><input type="hidden" name="spell_key" value="<?php echo esc_attr($isNew?'':(string)$selectedSpell['key']);?>"><?php wp_nonce_field('gmrc_save_steward_spell_'.($isNew?'new':(string)$selectedSpell['key']),'gmrc_steward_spell_nonce');?><header><div><p class="gmrc-stewards-office__eyebrow"><?php echo $isNew?'New shared spell':'Editing Steward spell';?></p><h2><?php echo esc_html($isNew?'Untitled Spell':(string)$selectedSpell['name']);?></h2></div><span class="gmrc-stewards-office__status"><?php echo esc_html(ucfirst($status));?></span></header>
<div class="gmrc-canonical-steward__fields"><label><strong>Name</strong><input name="name" type="text" required value="<?php echo esc_attr($value('name'));?>"></label><label><strong>Publication</strong><select name="status"><option value="draft"<?php selected($status,'draft');?>>Draft</option><option value="published"<?php selected($status,'published');?>>Published</option><option value="archived"<?php selected($status,'archived');?>>Archived</option></select></label><label><strong>Spell level</strong><select name="level"><option value="">Not set</option><?php for($i=0;$i<=9;$i++):?><option value="<?php echo esc_attr((string)$i);?>"<?php selected((string)($selectedSpell['level']??''),(string)$i);?>><?php echo $i===0?'Cantrip':'Level '.$i;?></option><?php endfor;?></select></label><label><strong>School</strong><select name="school"><option value="">Not set</option><?php foreach(['abjuration','conjuration','divination','enchantment','evocation','illusion','necromancy','transmutation'] as $school):?><option value="<?php echo esc_attr($school);?>"<?php selected($value('school'),$school);?>><?php echo esc_html(ucfirst($school));?></option><?php endforeach;?></select></label><label><strong>Casting time</strong><input name="casting_time" type="text" value="<?php echo esc_attr($value('casting_time'));?>" placeholder="1 action"></label><label><strong>Range</strong><input name="range" type="text" value="<?php echo esc_attr($value('range'));?>" placeholder="60 ft"></label><label><strong>Components</strong><input name="components" type="text" value="<?php echo esc_attr($value('components'));?>" placeholder="V, S, M (...)"></label><label><strong>Duration</strong><input name="duration" type="text" value="<?php echo esc_attr($value('duration'));?>" placeholder="Instantaneous"></label></div>
<fieldset class="gmrc-spell-workshop__access"><legend>Class access</legend><?php foreach(SpellWorkshop::ACCESS as $class):?><label><input type="checkbox" name="access_labels[]" value="<?php echo esc_attr($class);?>"<?php checked(in_array($class,$checkedAccess,true));?>> <?php echo esc_html($class);?></label><?php endforeach;?></fieldset>
<div class="gmrc-spell-workshop__toggles"><label><input name="ritual" type="checkbox" value="1"<?php checked(!empty($selectedSpell['ritual']));?>> Ritual</label><label><input name="concentration" type="checkbox" value="1"<?php checked(!empty($selectedSpell['concentration']));?>> Concentration</label></div>
<label><strong>Rules text</strong><textarea name="rules_text" rows="8" placeholder="Describe the spell’s complete effect."><?php echo esc_textarea($value('rules_text'));?></textarea></label><label><strong>At higher levels</strong><textarea name="higher_levels" rows="4"><?php echo esc_textarea($value('higher_levels'));?></textarea></label>
<section class="gmrc-spell-workshop__mechanics"><h3>Optional live-roll mechanics</h3><p>These fields let the Character Ledger offer a safe shared roll when the spell has a simple damage or healing formula.</p><div class="gmrc-canonical-steward__fields"><label><strong>Roll kind</strong><select name="roll_kind"><option value="">No automatic roll</option><option value="damage"<?php selected($value('roll_kind'),'damage');?>>Damage</option><option value="healing"<?php selected($value('roll_kind'),'healing');?>>Healing</option></select></label><label><strong>Dice formula</strong><input name="formula" type="text" value="<?php echo esc_attr($value('formula'));?>" placeholder="2d6"></label><label><strong>Damage type</strong><input name="damage_type" type="text" value="<?php echo esc_attr($value('damage_type'));?>"></label><label><strong>Saving throw</strong><select name="save_ability"><option value="">None</option><?php foreach(['strength','dexterity','constitution','intelligence','wisdom','charisma'] as $ability):?><option value="<?php echo esc_attr($ability);?>"<?php selected($value('save_ability'),$ability);?>><?php echo esc_html(ucfirst($ability));?></option><?php endforeach;?></select></label></div><div class="gmrc-spell-workshop__toggles"><label><input name="spell_attack" type="checkbox" value="1"<?php checked(!empty($selectedSpell['spell_attack']));?>> Spell attack roll</label><label><input name="add_casting_modifier" type="checkbox" value="1"<?php checked(!empty($selectedSpell['add_casting_modifier']));?>> Add casting modifier</label></div></section>
<label><strong>Steward notes</strong><textarea name="steward_notes" rows="5" placeholder="Balance notes, table rulings, design intent…"><?php echo esc_textarea($value('steward_notes'));?></textarea></label><aside class="gmrc-canonical-steward__source"><strong>Publication safeguard:</strong> Published spells must provide level, school, at least one supported class, casting time, range, duration and complete rules text. Their stable `steward-spell-*` identity cannot overwrite a canonical Handbook spell.</aside><div class="gmrc-canonical-steward__actions"><button class="button button-primary button-large" type="submit"><?php echo $isNew?'Create Steward Spell':'Seal Steward Spell';?></button><a class="button" href="<?php echo esc_url($recordsUrl);?>">New spell</a></div></form></main>
</div></div>
