<?php defined('ABSPATH') || exit; $editing=$session instanceof \GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Session; $attendance=$editing ? $session->attendance() : []; $attendingPlayers=array_map(static fn(array $row): int => (int)($row['player_id']??0),$attendance); $attendingCharacters=[]; foreach($attendance as $row){$attendingCharacters=array_merge($attendingCharacters,array_map('strval',$row['character_ids']??[]));} ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-session-form__body">
<input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($route); ?>"><input type="hidden" name="_method" value="<?php echo $editing ? 'PUT' : 'POST'; ?>"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_session_'.$campaign->id())); ?>">
<div class="gmrc-session-form__row"><label>Session number<input type="number" min="1" max="9999" name="session_number" required value="<?php echo esc_attr((string)($editing?$session->number():1)); ?>"></label><label>Date<input type="date" name="scheduled_date" value="<?php echo esc_attr($editing?$session->scheduledDate():''); ?>"></label><label>Status<select name="status"><option value="planned" <?php selected($editing?$session->status():'planned','planned'); ?>>Planned</option><option value="played" <?php selected($editing?$session->status():'planned','played'); ?>>Played</option><option value="cancelled" <?php selected($editing?$session->status():'planned','cancelled'); ?>>Cancelled</option></select></label></div>
<label>Session title<input type="text" name="title" maxlength="120" required value="<?php echo esc_attr($editing?$session->title():''); ?>"></label>
<label>Dungeon Master preparation<textarea name="prep_notes" rows="7" maxlength="5000"><?php echo esc_textarea($editing?$session->prepNotes():''); ?></textarea></label>
<label>Session recap<textarea name="recap" rows="8" maxlength="10000"><?php echo esc_textarea($editing?$session->recap():''); ?></textarea></label>
<fieldset class="gmrc-session-attendance"><legend>Attendance from the Player Roster</legend><p>Only rostered Players and Characters already attached to this campaign can be recorded.</p>
<?php if (($roster ?? []) === []) : ?><p>No Players are rostered yet. You can still save this Session and add attendance later.</p><?php endif; ?>
<?php foreach (($roster ?? []) as $member) : $user=$member['user']; ?><article class="gmrc-session-attendee"><label class="gmrc-session-attendee__player"><input type="checkbox" name="attendance_player_ids[]" value="<?php echo esc_attr((string)$user->ID); ?>" <?php checked(in_array((int)$user->ID,$attendingPlayers,true)); ?>><strong><?php echo esc_html($user->display_name); ?></strong></label><div class="gmrc-session-attendee__characters"><?php foreach (($member['characters'] ?? []) as $character) : $cid=$character->id()->value(); ?><label><input type="checkbox" name="attendance_character_ids[]" value="<?php echo esc_attr($cid); ?>" <?php checked(in_array($cid,$attendingCharacters,true)); ?>><?php echo esc_html($character->name()->value()); ?></label><?php endforeach; ?></div></article><?php endforeach; ?>
</fieldset>
<button class="gmrc-session-button" type="submit"><?php echo $editing ? 'Update Session' : 'Enter Session in Ledger'; ?></button>
</form>
